/**
 * generated by Xtext 2.9.2
 */
package org.xtext.example.mydsl.myDsl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Rules</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.Rules#getRuleFragments <em>Rule Fragments</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getRules()
 * @model
 * @generated
 */
public interface Rules extends EObject
{
  /**
   * Returns the value of the '<em><b>Rule Fragments</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.mydsl.myDsl.RuleFragments}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Rule Fragments</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Rule Fragments</em>' containment reference list.
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getRules_RuleFragments()
   * @model containment="true"
   * @generated
   */
  EList<RuleFragments> getRuleFragments();

} // Rules
