/**
 * generated by Xtext 2.9.2
 */
package org.xtext.example.mydsl.myDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Sub Event</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.SubEvent#getAmountEvent <em>Amount Event</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.SubEvent#getEntity <em>Entity</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getSubEvent()
 * @model
 * @generated
 */
public interface SubEvent extends EObject
{
  /**
   * Returns the value of the '<em><b>Amount Event</b></em>' attribute.
   * The literals are from the enumeration {@link org.xtext.example.mydsl.myDsl.Action}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Amount Event</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Amount Event</em>' attribute.
   * @see org.xtext.example.mydsl.myDsl.Action
   * @see #setAmountEvent(Action)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getSubEvent_AmountEvent()
   * @model
   * @generated
   */
  Action getAmountEvent();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.SubEvent#getAmountEvent <em>Amount Event</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Amount Event</em>' attribute.
   * @see org.xtext.example.mydsl.myDsl.Action
   * @see #getAmountEvent()
   * @generated
   */
  void setAmountEvent(Action value);

  /**
   * Returns the value of the '<em><b>Entity</b></em>' attribute.
   * The literals are from the enumeration {@link org.xtext.example.mydsl.myDsl.Entity}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Entity</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Entity</em>' attribute.
   * @see org.xtext.example.mydsl.myDsl.Entity
   * @see #setEntity(Entity)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getSubEvent_Entity()
   * @model
   * @generated
   */
  Entity getEntity();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.SubEvent#getEntity <em>Entity</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Entity</em>' attribute.
   * @see org.xtext.example.mydsl.myDsl.Entity
   * @see #getEntity()
   * @generated
   */
  void setEntity(Entity value);

} // SubEvent
