/*
 * generated by Xtext 2.9.2
 */
package org.xtext.example.mydsl.idea.lang;

import com.intellij.psi.tree.IFileElementType;
import java.util.HashMap;
import java.util.Map;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.idea.lang.IElementTypeProvider;
import org.eclipse.xtext.psi.stubs.XtextFileElementType;
import org.eclipse.xtext.psi.stubs.XtextFileStub;
import org.eclipse.xtext.psi.tree.IGrammarAwareElementType;
import org.xtext.example.mydsl.idea.lang.psi.impl.MyDslFileImpl;
import org.xtext.example.mydsl.services.MyDslGrammarAccess;

public class MyDslElementTypeProvider implements IElementTypeProvider {

	public static final IFileElementType FILE_TYPE = new XtextFileElementType<XtextFileStub<MyDslFileImpl>>(MyDslLanguage.INSTANCE);

	private static final Map<EObject, IGrammarAwareElementType> GRAMMAR_ELEMENT_TYPE = new HashMap<EObject, IGrammarAwareElementType>();

	private static IGrammarAwareElementType associate(IGrammarAwareElementType grammarAwareElementType) {
		GRAMMAR_ELEMENT_TYPE.put(grammarAwareElementType.getGrammarElement(), grammarAwareElementType);
		return grammarAwareElementType;
	}

	private static final MyDslGrammarAccess GRAMMAR_ACCESS = MyDslLanguage.INSTANCE.getInstance(MyDslGrammarAccess.class);

	private static class RulesFactory {
		public static IGrammarAwareElementType createRulesElementType() {
			return new IGrammarAwareElementType("Rules_ELEMENT_TYPE", MyDslLanguage.INSTANCE, GRAMMAR_ACCESS.getRulesRule());
		}
		public static IGrammarAwareElementType createRules_RuleFragmentsAssignmentElementType() {
			return new IGrammarAwareElementType("Rules_RuleFragmentsAssignment_ELEMENT_TYPE", MyDslLanguage.INSTANCE, GRAMMAR_ACCESS.getRulesAccess().getRuleFragmentsAssignment());
		}
		public static IGrammarAwareElementType createRules_RuleFragmentsRuleFragmentsParserRuleCall_0ElementType() {
			return new IGrammarAwareElementType("Rules_RuleFragmentsRuleFragmentsParserRuleCall_0_ELEMENT_TYPE", MyDslLanguage.INSTANCE, GRAMMAR_ACCESS.getRulesAccess().getRuleFragmentsRuleFragmentsParserRuleCall_0());
		}
	}

	public static final IGrammarAwareElementType Rules_ELEMENT_TYPE = associate(RulesFactory.createRulesElementType());

	public static final IGrammarAwareElementType Rules_RuleFragmentsAssignment_ELEMENT_TYPE = associate(RulesFactory.createRules_RuleFragmentsAssignmentElementType());

	public static final IGrammarAwareElementType Rules_RuleFragmentsRuleFragmentsParserRuleCall_0_ELEMENT_TYPE = associate(RulesFactory.createRules_RuleFragmentsRuleFragmentsParserRuleCall_0ElementType());

	private static class RuleFragmentsFactory {
		public static IGrammarAwareElementType createRuleFragmentsElementType() {
			return new IGrammarAwareElementType("RuleFragments_ELEMENT_TYPE", MyDslLanguage.INSTANCE, GRAMMAR_ACCESS.getRuleFragmentsRule());
		}
		public static IGrammarAwareElementType createRuleFragments_GroupElementType() {
			return new IGrammarAwareElementType("RuleFragments_Group_ELEMENT_TYPE", MyDslLanguage.INSTANCE, GRAMMAR_ACCESS.getRuleFragmentsAccess().getGroup());
		}
		public static IGrammarAwareElementType createRuleFragments_CreateRuleKeyword_0ElementType() {
			return new IGrammarAwareElementType("RuleFragments_CreateRuleKeyword_0_ELEMENT_TYPE", MyDslLanguage.INSTANCE, GRAMMAR_ACCESS.getRuleFragmentsAccess().getCreateRuleKeyword_0());
		}
		public static IGrammarAwareElementType createRuleFragments_RuleNameAssignment_1ElementType() {
			return new IGrammarAwareElementType("RuleFragments_RuleNameAssignment_1_ELEMENT_TYPE", MyDslLanguage.INSTANCE, GRAMMAR_ACCESS.getRuleFragmentsAccess().getRuleNameAssignment_1());
		}
		public static IGrammarAwareElementType createRuleFragments_RuleNameIDTerminalRuleCall_1_0ElementType() {
			return new IGrammarAwareElementType("RuleFragments_RuleNameIDTerminalRuleCall_1_0_ELEMENT_TYPE", MyDslLanguage.INSTANCE, GRAMMAR_ACCESS.getRuleFragmentsAccess().getRuleNameIDTerminalRuleCall_1_0());
		}
		public static IGrammarAwareElementType createRuleFragments_LeftCurlyBracketKeyword_2ElementType() {
			return new IGrammarAwareElementType("RuleFragments_LeftCurlyBracketKeyword_2_ELEMENT_TYPE", MyDslLanguage.INSTANCE, GRAMMAR_ACCESS.getRuleFragmentsAccess().getLeftCurlyBracketKeyword_2());
		}
		public static IGrammarAwareElementType createRuleFragments_RuleBodyAssignment_3ElementType() {
			return new IGrammarAwareElementType("RuleFragments_RuleBodyAssignment_3_ELEMENT_TYPE", MyDslLanguage.INSTANCE, GRAMMAR_ACCESS.getRuleFragmentsAccess().getRuleBodyAssignment_3());
		}
		public static IGrammarAwareElementType createRuleFragments_RuleBodyRuleBodyParserRuleCall_3_0ElementType() {
			return new IGrammarAwareElementType("RuleFragments_RuleBodyRuleBodyParserRuleCall_3_0_ELEMENT_TYPE", MyDslLanguage.INSTANCE, GRAMMAR_ACCESS.getRuleFragmentsAccess().getRuleBodyRuleBodyParserRuleCall_3_0());
		}
		public static IGrammarAwareElementType createRuleFragments_RightCurlyBracketKeyword_4ElementType() {
			return new IGrammarAwareElementType("RuleFragments_RightCurlyBracketKeyword_4_ELEMENT_TYPE", MyDslLanguage.INSTANCE, GRAMMAR_ACCESS.getRuleFragmentsAccess().getRightCurlyBracketKeyword_4());
		}
	}

	public static final IGrammarAwareElementType RuleFragments_ELEMENT_TYPE = associate(RuleFragmentsFactory.createRuleFragmentsElementType());

	public static final IGrammarAwareElementType RuleFragments_Group_ELEMENT_TYPE = associate(RuleFragmentsFactory.createRuleFragments_GroupElementType());

	public static final IGrammarAwareElementType RuleFragments_CreateRuleKeyword_0_ELEMENT_TYPE = associate(RuleFragmentsFactory.createRuleFragments_CreateRuleKeyword_0ElementType());

	public static final IGrammarAwareElementType RuleFragments_RuleNameAssignment_1_ELEMENT_TYPE = associate(RuleFragmentsFactory.createRuleFragments_RuleNameAssignment_1ElementType());

	public static final IGrammarAwareElementType RuleFragments_RuleNameIDTerminalRuleCall_1_0_ELEMENT_TYPE = associate(RuleFragmentsFactory.createRuleFragments_RuleNameIDTerminalRuleCall_1_0ElementType());

	public static final IGrammarAwareElementType RuleFragments_LeftCurlyBracketKeyword_2_ELEMENT_TYPE = associate(RuleFragmentsFactory.createRuleFragments_LeftCurlyBracketKeyword_2ElementType());

	public static final IGrammarAwareElementType RuleFragments_RuleBodyAssignment_3_ELEMENT_TYPE = associate(RuleFragmentsFactory.createRuleFragments_RuleBodyAssignment_3ElementType());

	public static final IGrammarAwareElementType RuleFragments_RuleBodyRuleBodyParserRuleCall_3_0_ELEMENT_TYPE = associate(RuleFragmentsFactory.createRuleFragments_RuleBodyRuleBodyParserRuleCall_3_0ElementType());

	public static final IGrammarAwareElementType RuleFragments_RightCurlyBracketKeyword_4_ELEMENT_TYPE = associate(RuleFragmentsFactory.createRuleFragments_RightCurlyBracketKeyword_4ElementType());

	private static class RuleBodyFactory {
		public static IGrammarAwareElementType createRuleBodyElementType() {
			return new IGrammarAwareElementType("RuleBody_ELEMENT_TYPE", MyDslLanguage.INSTANCE, GRAMMAR_ACCESS.getRuleBodyRule());
		}
		public static IGrammarAwareElementType createRuleBody_GroupElementType() {
			return new IGrammarAwareElementType("RuleBody_Group_ELEMENT_TYPE", MyDslLanguage.INSTANCE, GRAMMAR_ACCESS.getRuleBodyAccess().getGroup());
		}
		public static IGrammarAwareElementType createRuleBody_WhenKeyword_0ElementType() {
			return new IGrammarAwareElementType("RuleBody_WhenKeyword_0_ELEMENT_TYPE", MyDslLanguage.INSTANCE, GRAMMAR_ACCESS.getRuleBodyAccess().getWhenKeyword_0());
		}
		public static IGrammarAwareElementType createRuleBody_PayerEventAssignment_1ElementType() {
			return new IGrammarAwareElementType("RuleBody_PayerEventAssignment_1_ELEMENT_TYPE", MyDslLanguage.INSTANCE, GRAMMAR_ACCESS.getRuleBodyAccess().getPayerEventAssignment_1());
		}
		public static IGrammarAwareElementType createRuleBody_PayerEventPayerEventParserRuleCall_1_0ElementType() {
			return new IGrammarAwareElementType("RuleBody_PayerEventPayerEventParserRuleCall_1_0_ELEMENT_TYPE", MyDslLanguage.INSTANCE, GRAMMAR_ACCESS.getRuleBodyAccess().getPayerEventPayerEventParserRuleCall_1_0());
		}
		public static IGrammarAwareElementType createRuleBody_SubEventAssignment_2ElementType() {
			return new IGrammarAwareElementType("RuleBody_SubEventAssignment_2_ELEMENT_TYPE", MyDslLanguage.INSTANCE, GRAMMAR_ACCESS.getRuleBodyAccess().getSubEventAssignment_2());
		}
		public static IGrammarAwareElementType createRuleBody_SubEventSubEventParserRuleCall_2_0ElementType() {
			return new IGrammarAwareElementType("RuleBody_SubEventSubEventParserRuleCall_2_0_ELEMENT_TYPE", MyDslLanguage.INSTANCE, GRAMMAR_ACCESS.getRuleBodyAccess().getSubEventSubEventParserRuleCall_2_0());
		}
	}

	public static final IGrammarAwareElementType RuleBody_ELEMENT_TYPE = associate(RuleBodyFactory.createRuleBodyElementType());

	public static final IGrammarAwareElementType RuleBody_Group_ELEMENT_TYPE = associate(RuleBodyFactory.createRuleBody_GroupElementType());

	public static final IGrammarAwareElementType RuleBody_WhenKeyword_0_ELEMENT_TYPE = associate(RuleBodyFactory.createRuleBody_WhenKeyword_0ElementType());

	public static final IGrammarAwareElementType RuleBody_PayerEventAssignment_1_ELEMENT_TYPE = associate(RuleBodyFactory.createRuleBody_PayerEventAssignment_1ElementType());

	public static final IGrammarAwareElementType RuleBody_PayerEventPayerEventParserRuleCall_1_0_ELEMENT_TYPE = associate(RuleBodyFactory.createRuleBody_PayerEventPayerEventParserRuleCall_1_0ElementType());

	public static final IGrammarAwareElementType RuleBody_SubEventAssignment_2_ELEMENT_TYPE = associate(RuleBodyFactory.createRuleBody_SubEventAssignment_2ElementType());

	public static final IGrammarAwareElementType RuleBody_SubEventSubEventParserRuleCall_2_0_ELEMENT_TYPE = associate(RuleBodyFactory.createRuleBody_SubEventSubEventParserRuleCall_2_0ElementType());

	private static class PayerEventFactory {
		public static IGrammarAwareElementType createPayerEventElementType() {
			return new IGrammarAwareElementType("PayerEvent_ELEMENT_TYPE", MyDslLanguage.INSTANCE, GRAMMAR_ACCESS.getPayerEventRule());
		}
		public static IGrammarAwareElementType createPayerEvent_GroupElementType() {
			return new IGrammarAwareElementType("PayerEvent_Group_ELEMENT_TYPE", MyDslLanguage.INSTANCE, GRAMMAR_ACCESS.getPayerEventAccess().getGroup());
		}
		public static IGrammarAwareElementType createPayerEvent_PayerNameAssignment_0ElementType() {
			return new IGrammarAwareElementType("PayerEvent_PayerNameAssignment_0_ELEMENT_TYPE", MyDslLanguage.INSTANCE, GRAMMAR_ACCESS.getPayerEventAccess().getPayerNameAssignment_0());
		}
		public static IGrammarAwareElementType createPayerEvent_PayerNamePayerNameEnumRuleCall_0_0ElementType() {
			return new IGrammarAwareElementType("PayerEvent_PayerNamePayerNameEnumRuleCall_0_0_ELEMENT_TYPE", MyDslLanguage.INSTANCE, GRAMMAR_ACCESS.getPayerEventAccess().getPayerNamePayerNameEnumRuleCall_0_0());
		}
		public static IGrammarAwareElementType createPayerEvent_PayerEventNameAssignment_1ElementType() {
			return new IGrammarAwareElementType("PayerEvent_PayerEventNameAssignment_1_ELEMENT_TYPE", MyDslLanguage.INSTANCE, GRAMMAR_ACCESS.getPayerEventAccess().getPayerEventNameAssignment_1());
		}
		public static IGrammarAwareElementType createPayerEvent_PayerEventNamePayerEventNameEnumRuleCall_1_0ElementType() {
			return new IGrammarAwareElementType("PayerEvent_PayerEventNamePayerEventNameEnumRuleCall_1_0_ELEMENT_TYPE", MyDslLanguage.INSTANCE, GRAMMAR_ACCESS.getPayerEventAccess().getPayerEventNamePayerEventNameEnumRuleCall_1_0());
		}
		public static IGrammarAwareElementType createPayerEvent_SymbolAssignment_2ElementType() {
			return new IGrammarAwareElementType("PayerEvent_SymbolAssignment_2_ELEMENT_TYPE", MyDslLanguage.INSTANCE, GRAMMAR_ACCESS.getPayerEventAccess().getSymbolAssignment_2());
		}
		public static IGrammarAwareElementType createPayerEvent_SymbolSymbolEnumRuleCall_2_0ElementType() {
			return new IGrammarAwareElementType("PayerEvent_SymbolSymbolEnumRuleCall_2_0_ELEMENT_TYPE", MyDslLanguage.INSTANCE, GRAMMAR_ACCESS.getPayerEventAccess().getSymbolSymbolEnumRuleCall_2_0());
		}
		public static IGrammarAwareElementType createPayerEvent_AmountAssignment_3ElementType() {
			return new IGrammarAwareElementType("PayerEvent_AmountAssignment_3_ELEMENT_TYPE", MyDslLanguage.INSTANCE, GRAMMAR_ACCESS.getPayerEventAccess().getAmountAssignment_3());
		}
		public static IGrammarAwareElementType createPayerEvent_AmountINTTerminalRuleCall_3_0ElementType() {
			return new IGrammarAwareElementType("PayerEvent_AmountINTTerminalRuleCall_3_0_ELEMENT_TYPE", MyDslLanguage.INSTANCE, GRAMMAR_ACCESS.getPayerEventAccess().getAmountINTTerminalRuleCall_3_0());
		}
	}

	public static final IGrammarAwareElementType PayerEvent_ELEMENT_TYPE = associate(PayerEventFactory.createPayerEventElementType());

	public static final IGrammarAwareElementType PayerEvent_Group_ELEMENT_TYPE = associate(PayerEventFactory.createPayerEvent_GroupElementType());

	public static final IGrammarAwareElementType PayerEvent_PayerNameAssignment_0_ELEMENT_TYPE = associate(PayerEventFactory.createPayerEvent_PayerNameAssignment_0ElementType());

	public static final IGrammarAwareElementType PayerEvent_PayerNamePayerNameEnumRuleCall_0_0_ELEMENT_TYPE = associate(PayerEventFactory.createPayerEvent_PayerNamePayerNameEnumRuleCall_0_0ElementType());

	public static final IGrammarAwareElementType PayerEvent_PayerEventNameAssignment_1_ELEMENT_TYPE = associate(PayerEventFactory.createPayerEvent_PayerEventNameAssignment_1ElementType());

	public static final IGrammarAwareElementType PayerEvent_PayerEventNamePayerEventNameEnumRuleCall_1_0_ELEMENT_TYPE = associate(PayerEventFactory.createPayerEvent_PayerEventNamePayerEventNameEnumRuleCall_1_0ElementType());

	public static final IGrammarAwareElementType PayerEvent_SymbolAssignment_2_ELEMENT_TYPE = associate(PayerEventFactory.createPayerEvent_SymbolAssignment_2ElementType());

	public static final IGrammarAwareElementType PayerEvent_SymbolSymbolEnumRuleCall_2_0_ELEMENT_TYPE = associate(PayerEventFactory.createPayerEvent_SymbolSymbolEnumRuleCall_2_0ElementType());

	public static final IGrammarAwareElementType PayerEvent_AmountAssignment_3_ELEMENT_TYPE = associate(PayerEventFactory.createPayerEvent_AmountAssignment_3ElementType());

	public static final IGrammarAwareElementType PayerEvent_AmountINTTerminalRuleCall_3_0_ELEMENT_TYPE = associate(PayerEventFactory.createPayerEvent_AmountINTTerminalRuleCall_3_0ElementType());

	private static class PayerNameFactory {
		public static IGrammarAwareElementType createPayerNameElementType() {
			return new IGrammarAwareElementType("PayerName_ELEMENT_TYPE", MyDslLanguage.INSTANCE, GRAMMAR_ACCESS.getPayerNameRule());
		}
		public static IGrammarAwareElementType createPayerName_AlternativesElementType() {
			return new IGrammarAwareElementType("PayerName_Alternatives_ELEMENT_TYPE", MyDslLanguage.INSTANCE, GRAMMAR_ACCESS.getPayerNameAccess().getAlternatives());
		}
		public static IGrammarAwareElementType createPayerName_MINDTREEEnumLiteralDeclaration_0ElementType() {
			return new IGrammarAwareElementType("PayerName_MINDTREEEnumLiteralDeclaration_0_ELEMENT_TYPE", MyDslLanguage.INSTANCE, GRAMMAR_ACCESS.getPayerNameAccess().getMINDTREEEnumLiteralDeclaration_0());
		}
		public static IGrammarAwareElementType createPayerName_MINDTREEMindtreeKeyword_0_0ElementType() {
			return new IGrammarAwareElementType("PayerName_MINDTREEMindtreeKeyword_0_0_ELEMENT_TYPE", MyDslLanguage.INSTANCE, GRAMMAR_ACCESS.getPayerNameAccess().getMINDTREEMindtreeKeyword_0_0());
		}
		public static IGrammarAwareElementType createPayerName_ROHITEnumLiteralDeclaration_1ElementType() {
			return new IGrammarAwareElementType("PayerName_ROHITEnumLiteralDeclaration_1_ELEMENT_TYPE", MyDslLanguage.INSTANCE, GRAMMAR_ACCESS.getPayerNameAccess().getROHITEnumLiteralDeclaration_1());
		}
		public static IGrammarAwareElementType createPayerName_ROHITRohitKeyword_1_0ElementType() {
			return new IGrammarAwareElementType("PayerName_ROHITRohitKeyword_1_0_ELEMENT_TYPE", MyDslLanguage.INSTANCE, GRAMMAR_ACCESS.getPayerNameAccess().getROHITRohitKeyword_1_0());
		}
		public static IGrammarAwareElementType createPayerName_ABHISHEKEnumLiteralDeclaration_2ElementType() {
			return new IGrammarAwareElementType("PayerName_ABHISHEKEnumLiteralDeclaration_2_ELEMENT_TYPE", MyDslLanguage.INSTANCE, GRAMMAR_ACCESS.getPayerNameAccess().getABHISHEKEnumLiteralDeclaration_2());
		}
		public static IGrammarAwareElementType createPayerName_ABHISHEKAbhishekKeyword_2_0ElementType() {
			return new IGrammarAwareElementType("PayerName_ABHISHEKAbhishekKeyword_2_0_ELEMENT_TYPE", MyDslLanguage.INSTANCE, GRAMMAR_ACCESS.getPayerNameAccess().getABHISHEKAbhishekKeyword_2_0());
		}
	}

	public static final IGrammarAwareElementType PayerName_ELEMENT_TYPE = associate(PayerNameFactory.createPayerNameElementType());

	public static final IGrammarAwareElementType PayerName_Alternatives_ELEMENT_TYPE = associate(PayerNameFactory.createPayerName_AlternativesElementType());

	public static final IGrammarAwareElementType PayerName_MINDTREEEnumLiteralDeclaration_0_ELEMENT_TYPE = associate(PayerNameFactory.createPayerName_MINDTREEEnumLiteralDeclaration_0ElementType());

	public static final IGrammarAwareElementType PayerName_MINDTREEMindtreeKeyword_0_0_ELEMENT_TYPE = associate(PayerNameFactory.createPayerName_MINDTREEMindtreeKeyword_0_0ElementType());

	public static final IGrammarAwareElementType PayerName_ROHITEnumLiteralDeclaration_1_ELEMENT_TYPE = associate(PayerNameFactory.createPayerName_ROHITEnumLiteralDeclaration_1ElementType());

	public static final IGrammarAwareElementType PayerName_ROHITRohitKeyword_1_0_ELEMENT_TYPE = associate(PayerNameFactory.createPayerName_ROHITRohitKeyword_1_0ElementType());

	public static final IGrammarAwareElementType PayerName_ABHISHEKEnumLiteralDeclaration_2_ELEMENT_TYPE = associate(PayerNameFactory.createPayerName_ABHISHEKEnumLiteralDeclaration_2ElementType());

	public static final IGrammarAwareElementType PayerName_ABHISHEKAbhishekKeyword_2_0_ELEMENT_TYPE = associate(PayerNameFactory.createPayerName_ABHISHEKAbhishekKeyword_2_0ElementType());

	private static class PayerEventNameFactory {
		public static IGrammarAwareElementType createPayerEventNameElementType() {
			return new IGrammarAwareElementType("PayerEventName_ELEMENT_TYPE", MyDslLanguage.INSTANCE, GRAMMAR_ACCESS.getPayerEventNameRule());
		}
		public static IGrammarAwareElementType createPayerEventName_AlternativesElementType() {
			return new IGrammarAwareElementType("PayerEventName_Alternatives_ELEMENT_TYPE", MyDslLanguage.INSTANCE, GRAMMAR_ACCESS.getPayerEventNameAccess().getAlternatives());
		}
		public static IGrammarAwareElementType createPayerEventName_CREDITEnumLiteralDeclaration_0ElementType() {
			return new IGrammarAwareElementType("PayerEventName_CREDITEnumLiteralDeclaration_0_ELEMENT_TYPE", MyDslLanguage.INSTANCE, GRAMMAR_ACCESS.getPayerEventNameAccess().getCREDITEnumLiteralDeclaration_0());
		}
		public static IGrammarAwareElementType createPayerEventName_CREDITCreditKeyword_0_0ElementType() {
			return new IGrammarAwareElementType("PayerEventName_CREDITCreditKeyword_0_0_ELEMENT_TYPE", MyDslLanguage.INSTANCE, GRAMMAR_ACCESS.getPayerEventNameAccess().getCREDITCreditKeyword_0_0());
		}
		public static IGrammarAwareElementType createPayerEventName_DEBITEnumLiteralDeclaration_1ElementType() {
			return new IGrammarAwareElementType("PayerEventName_DEBITEnumLiteralDeclaration_1_ELEMENT_TYPE", MyDslLanguage.INSTANCE, GRAMMAR_ACCESS.getPayerEventNameAccess().getDEBITEnumLiteralDeclaration_1());
		}
		public static IGrammarAwareElementType createPayerEventName_DEBITDebitKeyword_1_0ElementType() {
			return new IGrammarAwareElementType("PayerEventName_DEBITDebitKeyword_1_0_ELEMENT_TYPE", MyDslLanguage.INSTANCE, GRAMMAR_ACCESS.getPayerEventNameAccess().getDEBITDebitKeyword_1_0());
		}
	}

	public static final IGrammarAwareElementType PayerEventName_ELEMENT_TYPE = associate(PayerEventNameFactory.createPayerEventNameElementType());

	public static final IGrammarAwareElementType PayerEventName_Alternatives_ELEMENT_TYPE = associate(PayerEventNameFactory.createPayerEventName_AlternativesElementType());

	public static final IGrammarAwareElementType PayerEventName_CREDITEnumLiteralDeclaration_0_ELEMENT_TYPE = associate(PayerEventNameFactory.createPayerEventName_CREDITEnumLiteralDeclaration_0ElementType());

	public static final IGrammarAwareElementType PayerEventName_CREDITCreditKeyword_0_0_ELEMENT_TYPE = associate(PayerEventNameFactory.createPayerEventName_CREDITCreditKeyword_0_0ElementType());

	public static final IGrammarAwareElementType PayerEventName_DEBITEnumLiteralDeclaration_1_ELEMENT_TYPE = associate(PayerEventNameFactory.createPayerEventName_DEBITEnumLiteralDeclaration_1ElementType());

	public static final IGrammarAwareElementType PayerEventName_DEBITDebitKeyword_1_0_ELEMENT_TYPE = associate(PayerEventNameFactory.createPayerEventName_DEBITDebitKeyword_1_0ElementType());

	private static class SymbolFactory {
		public static IGrammarAwareElementType createSymbolElementType() {
			return new IGrammarAwareElementType("Symbol_ELEMENT_TYPE", MyDslLanguage.INSTANCE, GRAMMAR_ACCESS.getSymbolRule());
		}
		public static IGrammarAwareElementType createSymbol_AlternativesElementType() {
			return new IGrammarAwareElementType("Symbol_Alternatives_ELEMENT_TYPE", MyDslLanguage.INSTANCE, GRAMMAR_ACCESS.getSymbolAccess().getAlternatives());
		}
		public static IGrammarAwareElementType createSymbol_GREATEREnumLiteralDeclaration_0ElementType() {
			return new IGrammarAwareElementType("Symbol_GREATEREnumLiteralDeclaration_0_ELEMENT_TYPE", MyDslLanguage.INSTANCE, GRAMMAR_ACCESS.getSymbolAccess().getGREATEREnumLiteralDeclaration_0());
		}
		public static IGrammarAwareElementType createSymbol_GREATERLessThanSignKeyword_0_0ElementType() {
			return new IGrammarAwareElementType("Symbol_GREATERLessThanSignKeyword_0_0_ELEMENT_TYPE", MyDslLanguage.INSTANCE, GRAMMAR_ACCESS.getSymbolAccess().getGREATERLessThanSignKeyword_0_0());
		}
		public static IGrammarAwareElementType createSymbol_LESSEnumLiteralDeclaration_1ElementType() {
			return new IGrammarAwareElementType("Symbol_LESSEnumLiteralDeclaration_1_ELEMENT_TYPE", MyDslLanguage.INSTANCE, GRAMMAR_ACCESS.getSymbolAccess().getLESSEnumLiteralDeclaration_1());
		}
		public static IGrammarAwareElementType createSymbol_LESSGreaterThanSignKeyword_1_0ElementType() {
			return new IGrammarAwareElementType("Symbol_LESSGreaterThanSignKeyword_1_0_ELEMENT_TYPE", MyDslLanguage.INSTANCE, GRAMMAR_ACCESS.getSymbolAccess().getLESSGreaterThanSignKeyword_1_0());
		}
	}

	public static final IGrammarAwareElementType Symbol_ELEMENT_TYPE = associate(SymbolFactory.createSymbolElementType());

	public static final IGrammarAwareElementType Symbol_Alternatives_ELEMENT_TYPE = associate(SymbolFactory.createSymbol_AlternativesElementType());

	public static final IGrammarAwareElementType Symbol_GREATEREnumLiteralDeclaration_0_ELEMENT_TYPE = associate(SymbolFactory.createSymbol_GREATEREnumLiteralDeclaration_0ElementType());

	public static final IGrammarAwareElementType Symbol_GREATERLessThanSignKeyword_0_0_ELEMENT_TYPE = associate(SymbolFactory.createSymbol_GREATERLessThanSignKeyword_0_0ElementType());

	public static final IGrammarAwareElementType Symbol_LESSEnumLiteralDeclaration_1_ELEMENT_TYPE = associate(SymbolFactory.createSymbol_LESSEnumLiteralDeclaration_1ElementType());

	public static final IGrammarAwareElementType Symbol_LESSGreaterThanSignKeyword_1_0_ELEMENT_TYPE = associate(SymbolFactory.createSymbol_LESSGreaterThanSignKeyword_1_0ElementType());

	private static class SubEventFactory {
		public static IGrammarAwareElementType createSubEventElementType() {
			return new IGrammarAwareElementType("SubEvent_ELEMENT_TYPE", MyDslLanguage.INSTANCE, GRAMMAR_ACCESS.getSubEventRule());
		}
		public static IGrammarAwareElementType createSubEvent_GroupElementType() {
			return new IGrammarAwareElementType("SubEvent_Group_ELEMENT_TYPE", MyDslLanguage.INSTANCE, GRAMMAR_ACCESS.getSubEventAccess().getGroup());
		}
		public static IGrammarAwareElementType createSubEvent_ThenKeyword_0ElementType() {
			return new IGrammarAwareElementType("SubEvent_ThenKeyword_0_ELEMENT_TYPE", MyDslLanguage.INSTANCE, GRAMMAR_ACCESS.getSubEventAccess().getThenKeyword_0());
		}
		public static IGrammarAwareElementType createSubEvent_AmountEventAssignment_1ElementType() {
			return new IGrammarAwareElementType("SubEvent_AmountEventAssignment_1_ELEMENT_TYPE", MyDslLanguage.INSTANCE, GRAMMAR_ACCESS.getSubEventAccess().getAmountEventAssignment_1());
		}
		public static IGrammarAwareElementType createSubEvent_AmountEventAmountEventEnumRuleCall_1_0ElementType() {
			return new IGrammarAwareElementType("SubEvent_AmountEventAmountEventEnumRuleCall_1_0_ELEMENT_TYPE", MyDslLanguage.INSTANCE, GRAMMAR_ACCESS.getSubEventAccess().getAmountEventAmountEventEnumRuleCall_1_0());
		}
		public static IGrammarAwareElementType createSubEvent_AmountAssignment_2ElementType() {
			return new IGrammarAwareElementType("SubEvent_AmountAssignment_2_ELEMENT_TYPE", MyDslLanguage.INSTANCE, GRAMMAR_ACCESS.getSubEventAccess().getAmountAssignment_2());
		}
		public static IGrammarAwareElementType createSubEvent_AmountINTTerminalRuleCall_2_0ElementType() {
			return new IGrammarAwareElementType("SubEvent_AmountINTTerminalRuleCall_2_0_ELEMENT_TYPE", MyDslLanguage.INSTANCE, GRAMMAR_ACCESS.getSubEventAccess().getAmountINTTerminalRuleCall_2_0());
		}
		public static IGrammarAwareElementType createSubEvent_ToKeyword_3ElementType() {
			return new IGrammarAwareElementType("SubEvent_ToKeyword_3_ELEMENT_TYPE", MyDslLanguage.INSTANCE, GRAMMAR_ACCESS.getSubEventAccess().getToKeyword_3());
		}
		public static IGrammarAwareElementType createSubEvent_PayerNameAssignment_4ElementType() {
			return new IGrammarAwareElementType("SubEvent_PayerNameAssignment_4_ELEMENT_TYPE", MyDslLanguage.INSTANCE, GRAMMAR_ACCESS.getSubEventAccess().getPayerNameAssignment_4());
		}
		public static IGrammarAwareElementType createSubEvent_PayerNamePayerNameEnumRuleCall_4_0ElementType() {
			return new IGrammarAwareElementType("SubEvent_PayerNamePayerNameEnumRuleCall_4_0_ELEMENT_TYPE", MyDslLanguage.INSTANCE, GRAMMAR_ACCESS.getSubEventAccess().getPayerNamePayerNameEnumRuleCall_4_0());
		}
	}

	public static final IGrammarAwareElementType SubEvent_ELEMENT_TYPE = associate(SubEventFactory.createSubEventElementType());

	public static final IGrammarAwareElementType SubEvent_Group_ELEMENT_TYPE = associate(SubEventFactory.createSubEvent_GroupElementType());

	public static final IGrammarAwareElementType SubEvent_ThenKeyword_0_ELEMENT_TYPE = associate(SubEventFactory.createSubEvent_ThenKeyword_0ElementType());

	public static final IGrammarAwareElementType SubEvent_AmountEventAssignment_1_ELEMENT_TYPE = associate(SubEventFactory.createSubEvent_AmountEventAssignment_1ElementType());

	public static final IGrammarAwareElementType SubEvent_AmountEventAmountEventEnumRuleCall_1_0_ELEMENT_TYPE = associate(SubEventFactory.createSubEvent_AmountEventAmountEventEnumRuleCall_1_0ElementType());

	public static final IGrammarAwareElementType SubEvent_AmountAssignment_2_ELEMENT_TYPE = associate(SubEventFactory.createSubEvent_AmountAssignment_2ElementType());

	public static final IGrammarAwareElementType SubEvent_AmountINTTerminalRuleCall_2_0_ELEMENT_TYPE = associate(SubEventFactory.createSubEvent_AmountINTTerminalRuleCall_2_0ElementType());

	public static final IGrammarAwareElementType SubEvent_ToKeyword_3_ELEMENT_TYPE = associate(SubEventFactory.createSubEvent_ToKeyword_3ElementType());

	public static final IGrammarAwareElementType SubEvent_PayerNameAssignment_4_ELEMENT_TYPE = associate(SubEventFactory.createSubEvent_PayerNameAssignment_4ElementType());

	public static final IGrammarAwareElementType SubEvent_PayerNamePayerNameEnumRuleCall_4_0_ELEMENT_TYPE = associate(SubEventFactory.createSubEvent_PayerNamePayerNameEnumRuleCall_4_0ElementType());

	private static class AmountEventFactory {
		public static IGrammarAwareElementType createAmountEventElementType() {
			return new IGrammarAwareElementType("AmountEvent_ELEMENT_TYPE", MyDslLanguage.INSTANCE, GRAMMAR_ACCESS.getAmountEventRule());
		}
		public static IGrammarAwareElementType createAmountEvent_AlternativesElementType() {
			return new IGrammarAwareElementType("AmountEvent_Alternatives_ELEMENT_TYPE", MyDslLanguage.INSTANCE, GRAMMAR_ACCESS.getAmountEventAccess().getAlternatives());
		}
		public static IGrammarAwareElementType createAmountEvent_TRANSFEREnumLiteralDeclaration_0ElementType() {
			return new IGrammarAwareElementType("AmountEvent_TRANSFEREnumLiteralDeclaration_0_ELEMENT_TYPE", MyDslLanguage.INSTANCE, GRAMMAR_ACCESS.getAmountEventAccess().getTRANSFEREnumLiteralDeclaration_0());
		}
		public static IGrammarAwareElementType createAmountEvent_TRANSFERTransferKeyword_0_0ElementType() {
			return new IGrammarAwareElementType("AmountEvent_TRANSFERTransferKeyword_0_0_ELEMENT_TYPE", MyDslLanguage.INSTANCE, GRAMMAR_ACCESS.getAmountEventAccess().getTRANSFERTransferKeyword_0_0());
		}
		public static IGrammarAwareElementType createAmountEvent_REQUESTEnumLiteralDeclaration_1ElementType() {
			return new IGrammarAwareElementType("AmountEvent_REQUESTEnumLiteralDeclaration_1_ELEMENT_TYPE", MyDslLanguage.INSTANCE, GRAMMAR_ACCESS.getAmountEventAccess().getREQUESTEnumLiteralDeclaration_1());
		}
		public static IGrammarAwareElementType createAmountEvent_REQUESTRequestKeyword_1_0ElementType() {
			return new IGrammarAwareElementType("AmountEvent_REQUESTRequestKeyword_1_0_ELEMENT_TYPE", MyDslLanguage.INSTANCE, GRAMMAR_ACCESS.getAmountEventAccess().getREQUESTRequestKeyword_1_0());
		}
	}

	public static final IGrammarAwareElementType AmountEvent_ELEMENT_TYPE = associate(AmountEventFactory.createAmountEventElementType());

	public static final IGrammarAwareElementType AmountEvent_Alternatives_ELEMENT_TYPE = associate(AmountEventFactory.createAmountEvent_AlternativesElementType());

	public static final IGrammarAwareElementType AmountEvent_TRANSFEREnumLiteralDeclaration_0_ELEMENT_TYPE = associate(AmountEventFactory.createAmountEvent_TRANSFEREnumLiteralDeclaration_0ElementType());

	public static final IGrammarAwareElementType AmountEvent_TRANSFERTransferKeyword_0_0_ELEMENT_TYPE = associate(AmountEventFactory.createAmountEvent_TRANSFERTransferKeyword_0_0ElementType());

	public static final IGrammarAwareElementType AmountEvent_REQUESTEnumLiteralDeclaration_1_ELEMENT_TYPE = associate(AmountEventFactory.createAmountEvent_REQUESTEnumLiteralDeclaration_1ElementType());

	public static final IGrammarAwareElementType AmountEvent_REQUESTRequestKeyword_1_0_ELEMENT_TYPE = associate(AmountEventFactory.createAmountEvent_REQUESTRequestKeyword_1_0ElementType());

	@Override
	public IFileElementType getFileType() {
		return FILE_TYPE;
	}

	@Override
	public IGrammarAwareElementType findElementType(EObject grammarElement) {
		return GRAMMAR_ELEMENT_TYPE.get(grammarElement);
	}
	
	public IGrammarAwareElementType getRulesElementType() {
		return Rules_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getRules_RuleFragmentsAssignmentElementType() {
		return Rules_RuleFragmentsAssignment_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getRules_RuleFragmentsRuleFragmentsParserRuleCall_0ElementType() {
		return Rules_RuleFragmentsRuleFragmentsParserRuleCall_0_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getRuleFragmentsElementType() {
		return RuleFragments_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getRuleFragments_GroupElementType() {
		return RuleFragments_Group_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getRuleFragments_CreateRuleKeyword_0ElementType() {
		return RuleFragments_CreateRuleKeyword_0_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getRuleFragments_RuleNameAssignment_1ElementType() {
		return RuleFragments_RuleNameAssignment_1_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getRuleFragments_RuleNameIDTerminalRuleCall_1_0ElementType() {
		return RuleFragments_RuleNameIDTerminalRuleCall_1_0_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getRuleFragments_LeftCurlyBracketKeyword_2ElementType() {
		return RuleFragments_LeftCurlyBracketKeyword_2_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getRuleFragments_RuleBodyAssignment_3ElementType() {
		return RuleFragments_RuleBodyAssignment_3_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getRuleFragments_RuleBodyRuleBodyParserRuleCall_3_0ElementType() {
		return RuleFragments_RuleBodyRuleBodyParserRuleCall_3_0_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getRuleFragments_RightCurlyBracketKeyword_4ElementType() {
		return RuleFragments_RightCurlyBracketKeyword_4_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getRuleBodyElementType() {
		return RuleBody_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getRuleBody_GroupElementType() {
		return RuleBody_Group_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getRuleBody_WhenKeyword_0ElementType() {
		return RuleBody_WhenKeyword_0_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getRuleBody_PayerEventAssignment_1ElementType() {
		return RuleBody_PayerEventAssignment_1_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getRuleBody_PayerEventPayerEventParserRuleCall_1_0ElementType() {
		return RuleBody_PayerEventPayerEventParserRuleCall_1_0_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getRuleBody_SubEventAssignment_2ElementType() {
		return RuleBody_SubEventAssignment_2_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getRuleBody_SubEventSubEventParserRuleCall_2_0ElementType() {
		return RuleBody_SubEventSubEventParserRuleCall_2_0_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getPayerEventElementType() {
		return PayerEvent_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getPayerEvent_GroupElementType() {
		return PayerEvent_Group_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getPayerEvent_PayerNameAssignment_0ElementType() {
		return PayerEvent_PayerNameAssignment_0_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getPayerEvent_PayerNamePayerNameEnumRuleCall_0_0ElementType() {
		return PayerEvent_PayerNamePayerNameEnumRuleCall_0_0_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getPayerEvent_PayerEventNameAssignment_1ElementType() {
		return PayerEvent_PayerEventNameAssignment_1_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getPayerEvent_PayerEventNamePayerEventNameEnumRuleCall_1_0ElementType() {
		return PayerEvent_PayerEventNamePayerEventNameEnumRuleCall_1_0_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getPayerEvent_SymbolAssignment_2ElementType() {
		return PayerEvent_SymbolAssignment_2_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getPayerEvent_SymbolSymbolEnumRuleCall_2_0ElementType() {
		return PayerEvent_SymbolSymbolEnumRuleCall_2_0_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getPayerEvent_AmountAssignment_3ElementType() {
		return PayerEvent_AmountAssignment_3_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getPayerEvent_AmountINTTerminalRuleCall_3_0ElementType() {
		return PayerEvent_AmountINTTerminalRuleCall_3_0_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getPayerNameElementType() {
		return PayerName_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getPayerName_AlternativesElementType() {
		return PayerName_Alternatives_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getPayerName_MINDTREEEnumLiteralDeclaration_0ElementType() {
		return PayerName_MINDTREEEnumLiteralDeclaration_0_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getPayerName_MINDTREEMindtreeKeyword_0_0ElementType() {
		return PayerName_MINDTREEMindtreeKeyword_0_0_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getPayerName_ROHITEnumLiteralDeclaration_1ElementType() {
		return PayerName_ROHITEnumLiteralDeclaration_1_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getPayerName_ROHITRohitKeyword_1_0ElementType() {
		return PayerName_ROHITRohitKeyword_1_0_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getPayerName_ABHISHEKEnumLiteralDeclaration_2ElementType() {
		return PayerName_ABHISHEKEnumLiteralDeclaration_2_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getPayerName_ABHISHEKAbhishekKeyword_2_0ElementType() {
		return PayerName_ABHISHEKAbhishekKeyword_2_0_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getPayerEventNameElementType() {
		return PayerEventName_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getPayerEventName_AlternativesElementType() {
		return PayerEventName_Alternatives_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getPayerEventName_CREDITEnumLiteralDeclaration_0ElementType() {
		return PayerEventName_CREDITEnumLiteralDeclaration_0_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getPayerEventName_CREDITCreditKeyword_0_0ElementType() {
		return PayerEventName_CREDITCreditKeyword_0_0_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getPayerEventName_DEBITEnumLiteralDeclaration_1ElementType() {
		return PayerEventName_DEBITEnumLiteralDeclaration_1_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getPayerEventName_DEBITDebitKeyword_1_0ElementType() {
		return PayerEventName_DEBITDebitKeyword_1_0_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getSymbolElementType() {
		return Symbol_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getSymbol_AlternativesElementType() {
		return Symbol_Alternatives_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getSymbol_GREATEREnumLiteralDeclaration_0ElementType() {
		return Symbol_GREATEREnumLiteralDeclaration_0_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getSymbol_GREATERLessThanSignKeyword_0_0ElementType() {
		return Symbol_GREATERLessThanSignKeyword_0_0_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getSymbol_LESSEnumLiteralDeclaration_1ElementType() {
		return Symbol_LESSEnumLiteralDeclaration_1_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getSymbol_LESSGreaterThanSignKeyword_1_0ElementType() {
		return Symbol_LESSGreaterThanSignKeyword_1_0_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getSubEventElementType() {
		return SubEvent_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getSubEvent_GroupElementType() {
		return SubEvent_Group_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getSubEvent_ThenKeyword_0ElementType() {
		return SubEvent_ThenKeyword_0_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getSubEvent_AmountEventAssignment_1ElementType() {
		return SubEvent_AmountEventAssignment_1_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getSubEvent_AmountEventAmountEventEnumRuleCall_1_0ElementType() {
		return SubEvent_AmountEventAmountEventEnumRuleCall_1_0_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getSubEvent_AmountAssignment_2ElementType() {
		return SubEvent_AmountAssignment_2_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getSubEvent_AmountINTTerminalRuleCall_2_0ElementType() {
		return SubEvent_AmountINTTerminalRuleCall_2_0_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getSubEvent_ToKeyword_3ElementType() {
		return SubEvent_ToKeyword_3_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getSubEvent_PayerNameAssignment_4ElementType() {
		return SubEvent_PayerNameAssignment_4_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getSubEvent_PayerNamePayerNameEnumRuleCall_4_0ElementType() {
		return SubEvent_PayerNamePayerNameEnumRuleCall_4_0_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getAmountEventElementType() {
		return AmountEvent_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getAmountEvent_AlternativesElementType() {
		return AmountEvent_Alternatives_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getAmountEvent_TRANSFEREnumLiteralDeclaration_0ElementType() {
		return AmountEvent_TRANSFEREnumLiteralDeclaration_0_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getAmountEvent_TRANSFERTransferKeyword_0_0ElementType() {
		return AmountEvent_TRANSFERTransferKeyword_0_0_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getAmountEvent_REQUESTEnumLiteralDeclaration_1ElementType() {
		return AmountEvent_REQUESTEnumLiteralDeclaration_1_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getAmountEvent_REQUESTRequestKeyword_1_0ElementType() {
		return AmountEvent_REQUESTRequestKeyword_1_0_ELEMENT_TYPE;
	}

}
