/**
 * generated by Xtext 2.9.2
 */
package org.xtext.example.mydsl.myDsl.impl;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.xtext.example.mydsl.myDsl.AmountEvent;
import org.xtext.example.mydsl.myDsl.MyDslPackage;
import org.xtext.example.mydsl.myDsl.PayerName;
import org.xtext.example.mydsl.myDsl.SubEvent;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Sub Event</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.impl.SubEventImpl#getAmountEvent <em>Amount Event</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.impl.SubEventImpl#getAmount <em>Amount</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.impl.SubEventImpl#getPayerName <em>Payer Name</em>}</li>
 * </ul>
 *
 * @generated
 */
public class SubEventImpl extends MinimalEObjectImpl.Container implements SubEvent
{
  /**
   * The default value of the '{@link #getAmountEvent() <em>Amount Event</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getAmountEvent()
   * @generated
   * @ordered
   */
  protected static final AmountEvent AMOUNT_EVENT_EDEFAULT = AmountEvent.TRANSFER;

  /**
   * The cached value of the '{@link #getAmountEvent() <em>Amount Event</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getAmountEvent()
   * @generated
   * @ordered
   */
  protected AmountEvent amountEvent = AMOUNT_EVENT_EDEFAULT;

  /**
   * The default value of the '{@link #getAmount() <em>Amount</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getAmount()
   * @generated
   * @ordered
   */
  protected static final int AMOUNT_EDEFAULT = 0;

  /**
   * The cached value of the '{@link #getAmount() <em>Amount</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getAmount()
   * @generated
   * @ordered
   */
  protected int amount = AMOUNT_EDEFAULT;

  /**
   * The default value of the '{@link #getPayerName() <em>Payer Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPayerName()
   * @generated
   * @ordered
   */
  protected static final PayerName PAYER_NAME_EDEFAULT = PayerName.MINDTREE;

  /**
   * The cached value of the '{@link #getPayerName() <em>Payer Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPayerName()
   * @generated
   * @ordered
   */
  protected PayerName payerName = PAYER_NAME_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected SubEventImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MyDslPackage.Literals.SUB_EVENT;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public AmountEvent getAmountEvent()
  {
    return amountEvent;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setAmountEvent(AmountEvent newAmountEvent)
  {
    AmountEvent oldAmountEvent = amountEvent;
    amountEvent = newAmountEvent == null ? AMOUNT_EVENT_EDEFAULT : newAmountEvent;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDslPackage.SUB_EVENT__AMOUNT_EVENT, oldAmountEvent, amountEvent));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public int getAmount()
  {
    return amount;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setAmount(int newAmount)
  {
    int oldAmount = amount;
    amount = newAmount;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDslPackage.SUB_EVENT__AMOUNT, oldAmount, amount));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public PayerName getPayerName()
  {
    return payerName;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setPayerName(PayerName newPayerName)
  {
    PayerName oldPayerName = payerName;
    payerName = newPayerName == null ? PAYER_NAME_EDEFAULT : newPayerName;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDslPackage.SUB_EVENT__PAYER_NAME, oldPayerName, payerName));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case MyDslPackage.SUB_EVENT__AMOUNT_EVENT:
        return getAmountEvent();
      case MyDslPackage.SUB_EVENT__AMOUNT:
        return getAmount();
      case MyDslPackage.SUB_EVENT__PAYER_NAME:
        return getPayerName();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case MyDslPackage.SUB_EVENT__AMOUNT_EVENT:
        setAmountEvent((AmountEvent)newValue);
        return;
      case MyDslPackage.SUB_EVENT__AMOUNT:
        setAmount((Integer)newValue);
        return;
      case MyDslPackage.SUB_EVENT__PAYER_NAME:
        setPayerName((PayerName)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case MyDslPackage.SUB_EVENT__AMOUNT_EVENT:
        setAmountEvent(AMOUNT_EVENT_EDEFAULT);
        return;
      case MyDslPackage.SUB_EVENT__AMOUNT:
        setAmount(AMOUNT_EDEFAULT);
        return;
      case MyDslPackage.SUB_EVENT__PAYER_NAME:
        setPayerName(PAYER_NAME_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case MyDslPackage.SUB_EVENT__AMOUNT_EVENT:
        return amountEvent != AMOUNT_EVENT_EDEFAULT;
      case MyDslPackage.SUB_EVENT__AMOUNT:
        return amount != AMOUNT_EDEFAULT;
      case MyDslPackage.SUB_EVENT__PAYER_NAME:
        return payerName != PAYER_NAME_EDEFAULT;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuffer result = new StringBuffer(super.toString());
    result.append(" (amountEvent: ");
    result.append(amountEvent);
    result.append(", amount: ");
    result.append(amount);
    result.append(", payerName: ");
    result.append(payerName);
    result.append(')');
    return result.toString();
  }

} //SubEventImpl
