/*
 * generated by Xtext 2.9.2
 */
package org.xtext.example.mydsl.ide.contentassist.antlr;

import com.google.inject.Inject;
import java.util.Collection;
import java.util.HashMap;
import java.util.Map;
import org.antlr.runtime.RecognitionException;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;
import org.eclipse.xtext.ide.editor.contentassist.antlr.FollowElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.internal.AbstractInternalContentAssistParser;
import org.xtext.example.mydsl.ide.contentassist.antlr.internal.InternalMyDslParser;
import org.xtext.example.mydsl.services.MyDslGrammarAccess;

public class MyDslParser extends AbstractContentAssistParser {

	@Inject
	private MyDslGrammarAccess grammarAccess;

	private Map<AbstractElement, String> nameMappings;

	@Override
	protected InternalMyDslParser createParser() {
		InternalMyDslParser result = new InternalMyDslParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		if (nameMappings == null) {
			nameMappings = new HashMap<AbstractElement, String>() {
				private static final long serialVersionUID = 1L;
				{
					put(grammarAccess.getAttributeAccess().getAlternatives(), "rule__Attribute__Alternatives");
					put(grammarAccess.getSymbolAccess().getAlternatives(), "rule__Symbol__Alternatives");
					put(grammarAccess.getActionAccess().getAlternatives(), "rule__Action__Alternatives");
					put(grammarAccess.getEntityAccess().getAlternatives(), "rule__Entity__Alternatives");
					put(grammarAccess.getRuleFragmentsAccess().getGroup(), "rule__RuleFragments__Group__0");
					put(grammarAccess.getRuleBodyAccess().getGroup(), "rule__RuleBody__Group__0");
					put(grammarAccess.getEventAccess().getGroup(), "rule__Event__Group__0");
					put(grammarAccess.getSubEventAccess().getGroup(), "rule__SubEvent__Group__0");
					put(grammarAccess.getRulesAccess().getRuleFragmentsAssignment(), "rule__Rules__RuleFragmentsAssignment");
					put(grammarAccess.getRuleFragmentsAccess().getRuleNameAssignment_1(), "rule__RuleFragments__RuleNameAssignment_1");
					put(grammarAccess.getRuleFragmentsAccess().getRuleBodyAssignment_3(), "rule__RuleFragments__RuleBodyAssignment_3");
					put(grammarAccess.getRuleBodyAccess().getEventAssignment_1(), "rule__RuleBody__EventAssignment_1");
					put(grammarAccess.getRuleBodyAccess().getSubEventAssignment_2(), "rule__RuleBody__SubEventAssignment_2");
					put(grammarAccess.getEventAccess().getAttributeAssignment_0(), "rule__Event__AttributeAssignment_0");
					put(grammarAccess.getEventAccess().getSymbolAssignment_1(), "rule__Event__SymbolAssignment_1");
					put(grammarAccess.getEventAccess().getValueAssignment_2(), "rule__Event__ValueAssignment_2");
					put(grammarAccess.getSubEventAccess().getAmountEventAssignment_1(), "rule__SubEvent__AmountEventAssignment_1");
					put(grammarAccess.getSubEventAccess().getEntityAssignment_2(), "rule__SubEvent__EntityAssignment_2");
				}
			};
		}
		return nameMappings.get(element);
	}

	@Override
	protected Collection<FollowElement> getFollowElements(AbstractInternalContentAssistParser parser) {
		try {
			InternalMyDslParser typedParser = (InternalMyDslParser) parser;
			typedParser.entryRuleRules();
			return typedParser.getFollowElements();
		} catch(RecognitionException ex) {
			throw new RuntimeException(ex);
		}
	}

	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public MyDslGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(MyDslGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
