/*
 * generated by Xtext 2.9.2
 */
package org.xtext.example.mydsl.idea.lang;

import com.intellij.psi.tree.IFileElementType;
import java.util.HashMap;
import java.util.Map;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.idea.lang.IElementTypeProvider;
import org.eclipse.xtext.psi.stubs.XtextFileElementType;
import org.eclipse.xtext.psi.stubs.XtextFileStub;
import org.eclipse.xtext.psi.tree.IGrammarAwareElementType;
import org.xtext.example.mydsl.idea.lang.psi.impl.MyDslFileImpl;
import org.xtext.example.mydsl.services.MyDslGrammarAccess;

public class MyDslElementTypeProvider implements IElementTypeProvider {

	public static final IFileElementType FILE_TYPE = new XtextFileElementType<XtextFileStub<MyDslFileImpl>>(MyDslLanguage.INSTANCE);

	private static final Map<EObject, IGrammarAwareElementType> GRAMMAR_ELEMENT_TYPE = new HashMap<EObject, IGrammarAwareElementType>();

	private static IGrammarAwareElementType associate(IGrammarAwareElementType grammarAwareElementType) {
		GRAMMAR_ELEMENT_TYPE.put(grammarAwareElementType.getGrammarElement(), grammarAwareElementType);
		return grammarAwareElementType;
	}

	private static final MyDslGrammarAccess GRAMMAR_ACCESS = MyDslLanguage.INSTANCE.getInstance(MyDslGrammarAccess.class);

	private static class RulesFactory {
		public static IGrammarAwareElementType createRulesElementType() {
			return new IGrammarAwareElementType("Rules_ELEMENT_TYPE", MyDslLanguage.INSTANCE, GRAMMAR_ACCESS.getRulesRule());
		}
		public static IGrammarAwareElementType createRules_RuleFragmentsAssignmentElementType() {
			return new IGrammarAwareElementType("Rules_RuleFragmentsAssignment_ELEMENT_TYPE", MyDslLanguage.INSTANCE, GRAMMAR_ACCESS.getRulesAccess().getRuleFragmentsAssignment());
		}
		public static IGrammarAwareElementType createRules_RuleFragmentsRuleFragmentsParserRuleCall_0ElementType() {
			return new IGrammarAwareElementType("Rules_RuleFragmentsRuleFragmentsParserRuleCall_0_ELEMENT_TYPE", MyDslLanguage.INSTANCE, GRAMMAR_ACCESS.getRulesAccess().getRuleFragmentsRuleFragmentsParserRuleCall_0());
		}
	}

	public static final IGrammarAwareElementType Rules_ELEMENT_TYPE = associate(RulesFactory.createRulesElementType());

	public static final IGrammarAwareElementType Rules_RuleFragmentsAssignment_ELEMENT_TYPE = associate(RulesFactory.createRules_RuleFragmentsAssignmentElementType());

	public static final IGrammarAwareElementType Rules_RuleFragmentsRuleFragmentsParserRuleCall_0_ELEMENT_TYPE = associate(RulesFactory.createRules_RuleFragmentsRuleFragmentsParserRuleCall_0ElementType());

	private static class RuleFragmentsFactory {
		public static IGrammarAwareElementType createRuleFragmentsElementType() {
			return new IGrammarAwareElementType("RuleFragments_ELEMENT_TYPE", MyDslLanguage.INSTANCE, GRAMMAR_ACCESS.getRuleFragmentsRule());
		}
		public static IGrammarAwareElementType createRuleFragments_GroupElementType() {
			return new IGrammarAwareElementType("RuleFragments_Group_ELEMENT_TYPE", MyDslLanguage.INSTANCE, GRAMMAR_ACCESS.getRuleFragmentsAccess().getGroup());
		}
		public static IGrammarAwareElementType createRuleFragments_RuleKeyword_0ElementType() {
			return new IGrammarAwareElementType("RuleFragments_RuleKeyword_0_ELEMENT_TYPE", MyDslLanguage.INSTANCE, GRAMMAR_ACCESS.getRuleFragmentsAccess().getRuleKeyword_0());
		}
		public static IGrammarAwareElementType createRuleFragments_RuleNameAssignment_1ElementType() {
			return new IGrammarAwareElementType("RuleFragments_RuleNameAssignment_1_ELEMENT_TYPE", MyDslLanguage.INSTANCE, GRAMMAR_ACCESS.getRuleFragmentsAccess().getRuleNameAssignment_1());
		}
		public static IGrammarAwareElementType createRuleFragments_RuleNameIDTerminalRuleCall_1_0ElementType() {
			return new IGrammarAwareElementType("RuleFragments_RuleNameIDTerminalRuleCall_1_0_ELEMENT_TYPE", MyDslLanguage.INSTANCE, GRAMMAR_ACCESS.getRuleFragmentsAccess().getRuleNameIDTerminalRuleCall_1_0());
		}
		public static IGrammarAwareElementType createRuleFragments_LeftCurlyBracketKeyword_2ElementType() {
			return new IGrammarAwareElementType("RuleFragments_LeftCurlyBracketKeyword_2_ELEMENT_TYPE", MyDslLanguage.INSTANCE, GRAMMAR_ACCESS.getRuleFragmentsAccess().getLeftCurlyBracketKeyword_2());
		}
		public static IGrammarAwareElementType createRuleFragments_RuleBodyAssignment_3ElementType() {
			return new IGrammarAwareElementType("RuleFragments_RuleBodyAssignment_3_ELEMENT_TYPE", MyDslLanguage.INSTANCE, GRAMMAR_ACCESS.getRuleFragmentsAccess().getRuleBodyAssignment_3());
		}
		public static IGrammarAwareElementType createRuleFragments_RuleBodyRuleBodyParserRuleCall_3_0ElementType() {
			return new IGrammarAwareElementType("RuleFragments_RuleBodyRuleBodyParserRuleCall_3_0_ELEMENT_TYPE", MyDslLanguage.INSTANCE, GRAMMAR_ACCESS.getRuleFragmentsAccess().getRuleBodyRuleBodyParserRuleCall_3_0());
		}
		public static IGrammarAwareElementType createRuleFragments_RightCurlyBracketKeyword_4ElementType() {
			return new IGrammarAwareElementType("RuleFragments_RightCurlyBracketKeyword_4_ELEMENT_TYPE", MyDslLanguage.INSTANCE, GRAMMAR_ACCESS.getRuleFragmentsAccess().getRightCurlyBracketKeyword_4());
		}
	}

	public static final IGrammarAwareElementType RuleFragments_ELEMENT_TYPE = associate(RuleFragmentsFactory.createRuleFragmentsElementType());

	public static final IGrammarAwareElementType RuleFragments_Group_ELEMENT_TYPE = associate(RuleFragmentsFactory.createRuleFragments_GroupElementType());

	public static final IGrammarAwareElementType RuleFragments_RuleKeyword_0_ELEMENT_TYPE = associate(RuleFragmentsFactory.createRuleFragments_RuleKeyword_0ElementType());

	public static final IGrammarAwareElementType RuleFragments_RuleNameAssignment_1_ELEMENT_TYPE = associate(RuleFragmentsFactory.createRuleFragments_RuleNameAssignment_1ElementType());

	public static final IGrammarAwareElementType RuleFragments_RuleNameIDTerminalRuleCall_1_0_ELEMENT_TYPE = associate(RuleFragmentsFactory.createRuleFragments_RuleNameIDTerminalRuleCall_1_0ElementType());

	public static final IGrammarAwareElementType RuleFragments_LeftCurlyBracketKeyword_2_ELEMENT_TYPE = associate(RuleFragmentsFactory.createRuleFragments_LeftCurlyBracketKeyword_2ElementType());

	public static final IGrammarAwareElementType RuleFragments_RuleBodyAssignment_3_ELEMENT_TYPE = associate(RuleFragmentsFactory.createRuleFragments_RuleBodyAssignment_3ElementType());

	public static final IGrammarAwareElementType RuleFragments_RuleBodyRuleBodyParserRuleCall_3_0_ELEMENT_TYPE = associate(RuleFragmentsFactory.createRuleFragments_RuleBodyRuleBodyParserRuleCall_3_0ElementType());

	public static final IGrammarAwareElementType RuleFragments_RightCurlyBracketKeyword_4_ELEMENT_TYPE = associate(RuleFragmentsFactory.createRuleFragments_RightCurlyBracketKeyword_4ElementType());

	private static class RuleBodyFactory {
		public static IGrammarAwareElementType createRuleBodyElementType() {
			return new IGrammarAwareElementType("RuleBody_ELEMENT_TYPE", MyDslLanguage.INSTANCE, GRAMMAR_ACCESS.getRuleBodyRule());
		}
		public static IGrammarAwareElementType createRuleBody_GroupElementType() {
			return new IGrammarAwareElementType("RuleBody_Group_ELEMENT_TYPE", MyDslLanguage.INSTANCE, GRAMMAR_ACCESS.getRuleBodyAccess().getGroup());
		}
		public static IGrammarAwareElementType createRuleBody_WhenKeyword_0ElementType() {
			return new IGrammarAwareElementType("RuleBody_WhenKeyword_0_ELEMENT_TYPE", MyDslLanguage.INSTANCE, GRAMMAR_ACCESS.getRuleBodyAccess().getWhenKeyword_0());
		}
		public static IGrammarAwareElementType createRuleBody_EventAssignment_1ElementType() {
			return new IGrammarAwareElementType("RuleBody_EventAssignment_1_ELEMENT_TYPE", MyDslLanguage.INSTANCE, GRAMMAR_ACCESS.getRuleBodyAccess().getEventAssignment_1());
		}
		public static IGrammarAwareElementType createRuleBody_EventEventParserRuleCall_1_0ElementType() {
			return new IGrammarAwareElementType("RuleBody_EventEventParserRuleCall_1_0_ELEMENT_TYPE", MyDslLanguage.INSTANCE, GRAMMAR_ACCESS.getRuleBodyAccess().getEventEventParserRuleCall_1_0());
		}
		public static IGrammarAwareElementType createRuleBody_SubEventAssignment_2ElementType() {
			return new IGrammarAwareElementType("RuleBody_SubEventAssignment_2_ELEMENT_TYPE", MyDslLanguage.INSTANCE, GRAMMAR_ACCESS.getRuleBodyAccess().getSubEventAssignment_2());
		}
		public static IGrammarAwareElementType createRuleBody_SubEventSubEventParserRuleCall_2_0ElementType() {
			return new IGrammarAwareElementType("RuleBody_SubEventSubEventParserRuleCall_2_0_ELEMENT_TYPE", MyDslLanguage.INSTANCE, GRAMMAR_ACCESS.getRuleBodyAccess().getSubEventSubEventParserRuleCall_2_0());
		}
	}

	public static final IGrammarAwareElementType RuleBody_ELEMENT_TYPE = associate(RuleBodyFactory.createRuleBodyElementType());

	public static final IGrammarAwareElementType RuleBody_Group_ELEMENT_TYPE = associate(RuleBodyFactory.createRuleBody_GroupElementType());

	public static final IGrammarAwareElementType RuleBody_WhenKeyword_0_ELEMENT_TYPE = associate(RuleBodyFactory.createRuleBody_WhenKeyword_0ElementType());

	public static final IGrammarAwareElementType RuleBody_EventAssignment_1_ELEMENT_TYPE = associate(RuleBodyFactory.createRuleBody_EventAssignment_1ElementType());

	public static final IGrammarAwareElementType RuleBody_EventEventParserRuleCall_1_0_ELEMENT_TYPE = associate(RuleBodyFactory.createRuleBody_EventEventParserRuleCall_1_0ElementType());

	public static final IGrammarAwareElementType RuleBody_SubEventAssignment_2_ELEMENT_TYPE = associate(RuleBodyFactory.createRuleBody_SubEventAssignment_2ElementType());

	public static final IGrammarAwareElementType RuleBody_SubEventSubEventParserRuleCall_2_0_ELEMENT_TYPE = associate(RuleBodyFactory.createRuleBody_SubEventSubEventParserRuleCall_2_0ElementType());

	private static class EventFactory {
		public static IGrammarAwareElementType createEventElementType() {
			return new IGrammarAwareElementType("Event_ELEMENT_TYPE", MyDslLanguage.INSTANCE, GRAMMAR_ACCESS.getEventRule());
		}
		public static IGrammarAwareElementType createEvent_GroupElementType() {
			return new IGrammarAwareElementType("Event_Group_ELEMENT_TYPE", MyDslLanguage.INSTANCE, GRAMMAR_ACCESS.getEventAccess().getGroup());
		}
		public static IGrammarAwareElementType createEvent_AttributeAssignment_0ElementType() {
			return new IGrammarAwareElementType("Event_AttributeAssignment_0_ELEMENT_TYPE", MyDslLanguage.INSTANCE, GRAMMAR_ACCESS.getEventAccess().getAttributeAssignment_0());
		}
		public static IGrammarAwareElementType createEvent_AttributeAttributeEnumRuleCall_0_0ElementType() {
			return new IGrammarAwareElementType("Event_AttributeAttributeEnumRuleCall_0_0_ELEMENT_TYPE", MyDslLanguage.INSTANCE, GRAMMAR_ACCESS.getEventAccess().getAttributeAttributeEnumRuleCall_0_0());
		}
		public static IGrammarAwareElementType createEvent_SymbolAssignment_1ElementType() {
			return new IGrammarAwareElementType("Event_SymbolAssignment_1_ELEMENT_TYPE", MyDslLanguage.INSTANCE, GRAMMAR_ACCESS.getEventAccess().getSymbolAssignment_1());
		}
		public static IGrammarAwareElementType createEvent_SymbolSymbolEnumRuleCall_1_0ElementType() {
			return new IGrammarAwareElementType("Event_SymbolSymbolEnumRuleCall_1_0_ELEMENT_TYPE", MyDslLanguage.INSTANCE, GRAMMAR_ACCESS.getEventAccess().getSymbolSymbolEnumRuleCall_1_0());
		}
		public static IGrammarAwareElementType createEvent_ValueAssignment_2ElementType() {
			return new IGrammarAwareElementType("Event_ValueAssignment_2_ELEMENT_TYPE", MyDslLanguage.INSTANCE, GRAMMAR_ACCESS.getEventAccess().getValueAssignment_2());
		}
		public static IGrammarAwareElementType createEvent_ValueINTTerminalRuleCall_2_0ElementType() {
			return new IGrammarAwareElementType("Event_ValueINTTerminalRuleCall_2_0_ELEMENT_TYPE", MyDslLanguage.INSTANCE, GRAMMAR_ACCESS.getEventAccess().getValueINTTerminalRuleCall_2_0());
		}
	}

	public static final IGrammarAwareElementType Event_ELEMENT_TYPE = associate(EventFactory.createEventElementType());

	public static final IGrammarAwareElementType Event_Group_ELEMENT_TYPE = associate(EventFactory.createEvent_GroupElementType());

	public static final IGrammarAwareElementType Event_AttributeAssignment_0_ELEMENT_TYPE = associate(EventFactory.createEvent_AttributeAssignment_0ElementType());

	public static final IGrammarAwareElementType Event_AttributeAttributeEnumRuleCall_0_0_ELEMENT_TYPE = associate(EventFactory.createEvent_AttributeAttributeEnumRuleCall_0_0ElementType());

	public static final IGrammarAwareElementType Event_SymbolAssignment_1_ELEMENT_TYPE = associate(EventFactory.createEvent_SymbolAssignment_1ElementType());

	public static final IGrammarAwareElementType Event_SymbolSymbolEnumRuleCall_1_0_ELEMENT_TYPE = associate(EventFactory.createEvent_SymbolSymbolEnumRuleCall_1_0ElementType());

	public static final IGrammarAwareElementType Event_ValueAssignment_2_ELEMENT_TYPE = associate(EventFactory.createEvent_ValueAssignment_2ElementType());

	public static final IGrammarAwareElementType Event_ValueINTTerminalRuleCall_2_0_ELEMENT_TYPE = associate(EventFactory.createEvent_ValueINTTerminalRuleCall_2_0ElementType());

	private static class AttributeFactory {
		public static IGrammarAwareElementType createAttributeElementType() {
			return new IGrammarAwareElementType("Attribute_ELEMENT_TYPE", MyDslLanguage.INSTANCE, GRAMMAR_ACCESS.getAttributeRule());
		}
		public static IGrammarAwareElementType createAttribute_AlternativesElementType() {
			return new IGrammarAwareElementType("Attribute_Alternatives_ELEMENT_TYPE", MyDslLanguage.INSTANCE, GRAMMAR_ACCESS.getAttributeAccess().getAlternatives());
		}
		public static IGrammarAwareElementType createAttribute_TEMPERATUREEnumLiteralDeclaration_0ElementType() {
			return new IGrammarAwareElementType("Attribute_TEMPERATUREEnumLiteralDeclaration_0_ELEMENT_TYPE", MyDslLanguage.INSTANCE, GRAMMAR_ACCESS.getAttributeAccess().getTEMPERATUREEnumLiteralDeclaration_0());
		}
		public static IGrammarAwareElementType createAttribute_TEMPERATURETemperatureKeyword_0_0ElementType() {
			return new IGrammarAwareElementType("Attribute_TEMPERATURETemperatureKeyword_0_0_ELEMENT_TYPE", MyDslLanguage.INSTANCE, GRAMMAR_ACCESS.getAttributeAccess().getTEMPERATURETemperatureKeyword_0_0());
		}
		public static IGrammarAwareElementType createAttribute_VIBRATIONEnumLiteralDeclaration_1ElementType() {
			return new IGrammarAwareElementType("Attribute_VIBRATIONEnumLiteralDeclaration_1_ELEMENT_TYPE", MyDslLanguage.INSTANCE, GRAMMAR_ACCESS.getAttributeAccess().getVIBRATIONEnumLiteralDeclaration_1());
		}
		public static IGrammarAwareElementType createAttribute_VIBRATIONVibrationKeyword_1_0ElementType() {
			return new IGrammarAwareElementType("Attribute_VIBRATIONVibrationKeyword_1_0_ELEMENT_TYPE", MyDslLanguage.INSTANCE, GRAMMAR_ACCESS.getAttributeAccess().getVIBRATIONVibrationKeyword_1_0());
		}
		public static IGrammarAwareElementType createAttribute_HUMIDITYEnumLiteralDeclaration_2ElementType() {
			return new IGrammarAwareElementType("Attribute_HUMIDITYEnumLiteralDeclaration_2_ELEMENT_TYPE", MyDslLanguage.INSTANCE, GRAMMAR_ACCESS.getAttributeAccess().getHUMIDITYEnumLiteralDeclaration_2());
		}
		public static IGrammarAwareElementType createAttribute_HUMIDITYHumidityKeyword_2_0ElementType() {
			return new IGrammarAwareElementType("Attribute_HUMIDITYHumidityKeyword_2_0_ELEMENT_TYPE", MyDslLanguage.INSTANCE, GRAMMAR_ACCESS.getAttributeAccess().getHUMIDITYHumidityKeyword_2_0());
		}
	}

	public static final IGrammarAwareElementType Attribute_ELEMENT_TYPE = associate(AttributeFactory.createAttributeElementType());

	public static final IGrammarAwareElementType Attribute_Alternatives_ELEMENT_TYPE = associate(AttributeFactory.createAttribute_AlternativesElementType());

	public static final IGrammarAwareElementType Attribute_TEMPERATUREEnumLiteralDeclaration_0_ELEMENT_TYPE = associate(AttributeFactory.createAttribute_TEMPERATUREEnumLiteralDeclaration_0ElementType());

	public static final IGrammarAwareElementType Attribute_TEMPERATURETemperatureKeyword_0_0_ELEMENT_TYPE = associate(AttributeFactory.createAttribute_TEMPERATURETemperatureKeyword_0_0ElementType());

	public static final IGrammarAwareElementType Attribute_VIBRATIONEnumLiteralDeclaration_1_ELEMENT_TYPE = associate(AttributeFactory.createAttribute_VIBRATIONEnumLiteralDeclaration_1ElementType());

	public static final IGrammarAwareElementType Attribute_VIBRATIONVibrationKeyword_1_0_ELEMENT_TYPE = associate(AttributeFactory.createAttribute_VIBRATIONVibrationKeyword_1_0ElementType());

	public static final IGrammarAwareElementType Attribute_HUMIDITYEnumLiteralDeclaration_2_ELEMENT_TYPE = associate(AttributeFactory.createAttribute_HUMIDITYEnumLiteralDeclaration_2ElementType());

	public static final IGrammarAwareElementType Attribute_HUMIDITYHumidityKeyword_2_0_ELEMENT_TYPE = associate(AttributeFactory.createAttribute_HUMIDITYHumidityKeyword_2_0ElementType());

	private static class SymbolFactory {
		public static IGrammarAwareElementType createSymbolElementType() {
			return new IGrammarAwareElementType("Symbol_ELEMENT_TYPE", MyDslLanguage.INSTANCE, GRAMMAR_ACCESS.getSymbolRule());
		}
		public static IGrammarAwareElementType createSymbol_AlternativesElementType() {
			return new IGrammarAwareElementType("Symbol_Alternatives_ELEMENT_TYPE", MyDslLanguage.INSTANCE, GRAMMAR_ACCESS.getSymbolAccess().getAlternatives());
		}
		public static IGrammarAwareElementType createSymbol_GREATEREnumLiteralDeclaration_0ElementType() {
			return new IGrammarAwareElementType("Symbol_GREATEREnumLiteralDeclaration_0_ELEMENT_TYPE", MyDslLanguage.INSTANCE, GRAMMAR_ACCESS.getSymbolAccess().getGREATEREnumLiteralDeclaration_0());
		}
		public static IGrammarAwareElementType createSymbol_GREATERLessThanSignKeyword_0_0ElementType() {
			return new IGrammarAwareElementType("Symbol_GREATERLessThanSignKeyword_0_0_ELEMENT_TYPE", MyDslLanguage.INSTANCE, GRAMMAR_ACCESS.getSymbolAccess().getGREATERLessThanSignKeyword_0_0());
		}
		public static IGrammarAwareElementType createSymbol_LESSEnumLiteralDeclaration_1ElementType() {
			return new IGrammarAwareElementType("Symbol_LESSEnumLiteralDeclaration_1_ELEMENT_TYPE", MyDslLanguage.INSTANCE, GRAMMAR_ACCESS.getSymbolAccess().getLESSEnumLiteralDeclaration_1());
		}
		public static IGrammarAwareElementType createSymbol_LESSGreaterThanSignKeyword_1_0ElementType() {
			return new IGrammarAwareElementType("Symbol_LESSGreaterThanSignKeyword_1_0_ELEMENT_TYPE", MyDslLanguage.INSTANCE, GRAMMAR_ACCESS.getSymbolAccess().getLESSGreaterThanSignKeyword_1_0());
		}
	}

	public static final IGrammarAwareElementType Symbol_ELEMENT_TYPE = associate(SymbolFactory.createSymbolElementType());

	public static final IGrammarAwareElementType Symbol_Alternatives_ELEMENT_TYPE = associate(SymbolFactory.createSymbol_AlternativesElementType());

	public static final IGrammarAwareElementType Symbol_GREATEREnumLiteralDeclaration_0_ELEMENT_TYPE = associate(SymbolFactory.createSymbol_GREATEREnumLiteralDeclaration_0ElementType());

	public static final IGrammarAwareElementType Symbol_GREATERLessThanSignKeyword_0_0_ELEMENT_TYPE = associate(SymbolFactory.createSymbol_GREATERLessThanSignKeyword_0_0ElementType());

	public static final IGrammarAwareElementType Symbol_LESSEnumLiteralDeclaration_1_ELEMENT_TYPE = associate(SymbolFactory.createSymbol_LESSEnumLiteralDeclaration_1ElementType());

	public static final IGrammarAwareElementType Symbol_LESSGreaterThanSignKeyword_1_0_ELEMENT_TYPE = associate(SymbolFactory.createSymbol_LESSGreaterThanSignKeyword_1_0ElementType());

	private static class SubEventFactory {
		public static IGrammarAwareElementType createSubEventElementType() {
			return new IGrammarAwareElementType("SubEvent_ELEMENT_TYPE", MyDslLanguage.INSTANCE, GRAMMAR_ACCESS.getSubEventRule());
		}
		public static IGrammarAwareElementType createSubEvent_GroupElementType() {
			return new IGrammarAwareElementType("SubEvent_Group_ELEMENT_TYPE", MyDslLanguage.INSTANCE, GRAMMAR_ACCESS.getSubEventAccess().getGroup());
		}
		public static IGrammarAwareElementType createSubEvent_ThenKeyword_0ElementType() {
			return new IGrammarAwareElementType("SubEvent_ThenKeyword_0_ELEMENT_TYPE", MyDslLanguage.INSTANCE, GRAMMAR_ACCESS.getSubEventAccess().getThenKeyword_0());
		}
		public static IGrammarAwareElementType createSubEvent_AmountEventAssignment_1ElementType() {
			return new IGrammarAwareElementType("SubEvent_AmountEventAssignment_1_ELEMENT_TYPE", MyDslLanguage.INSTANCE, GRAMMAR_ACCESS.getSubEventAccess().getAmountEventAssignment_1());
		}
		public static IGrammarAwareElementType createSubEvent_AmountEventActionEnumRuleCall_1_0ElementType() {
			return new IGrammarAwareElementType("SubEvent_AmountEventActionEnumRuleCall_1_0_ELEMENT_TYPE", MyDslLanguage.INSTANCE, GRAMMAR_ACCESS.getSubEventAccess().getAmountEventActionEnumRuleCall_1_0());
		}
		public static IGrammarAwareElementType createSubEvent_EntityAssignment_2ElementType() {
			return new IGrammarAwareElementType("SubEvent_EntityAssignment_2_ELEMENT_TYPE", MyDslLanguage.INSTANCE, GRAMMAR_ACCESS.getSubEventAccess().getEntityAssignment_2());
		}
		public static IGrammarAwareElementType createSubEvent_EntityEntityEnumRuleCall_2_0ElementType() {
			return new IGrammarAwareElementType("SubEvent_EntityEntityEnumRuleCall_2_0_ELEMENT_TYPE", MyDslLanguage.INSTANCE, GRAMMAR_ACCESS.getSubEventAccess().getEntityEntityEnumRuleCall_2_0());
		}
	}

	public static final IGrammarAwareElementType SubEvent_ELEMENT_TYPE = associate(SubEventFactory.createSubEventElementType());

	public static final IGrammarAwareElementType SubEvent_Group_ELEMENT_TYPE = associate(SubEventFactory.createSubEvent_GroupElementType());

	public static final IGrammarAwareElementType SubEvent_ThenKeyword_0_ELEMENT_TYPE = associate(SubEventFactory.createSubEvent_ThenKeyword_0ElementType());

	public static final IGrammarAwareElementType SubEvent_AmountEventAssignment_1_ELEMENT_TYPE = associate(SubEventFactory.createSubEvent_AmountEventAssignment_1ElementType());

	public static final IGrammarAwareElementType SubEvent_AmountEventActionEnumRuleCall_1_0_ELEMENT_TYPE = associate(SubEventFactory.createSubEvent_AmountEventActionEnumRuleCall_1_0ElementType());

	public static final IGrammarAwareElementType SubEvent_EntityAssignment_2_ELEMENT_TYPE = associate(SubEventFactory.createSubEvent_EntityAssignment_2ElementType());

	public static final IGrammarAwareElementType SubEvent_EntityEntityEnumRuleCall_2_0_ELEMENT_TYPE = associate(SubEventFactory.createSubEvent_EntityEntityEnumRuleCall_2_0ElementType());

	private static class ActionFactory {
		public static IGrammarAwareElementType createActionElementType() {
			return new IGrammarAwareElementType("Action_ELEMENT_TYPE", MyDslLanguage.INSTANCE, GRAMMAR_ACCESS.getActionRule());
		}
		public static IGrammarAwareElementType createAction_AlternativesElementType() {
			return new IGrammarAwareElementType("Action_Alternatives_ELEMENT_TYPE", MyDslLanguage.INSTANCE, GRAMMAR_ACCESS.getActionAccess().getAlternatives());
		}
		public static IGrammarAwareElementType createAction_TURN_ONEnumLiteralDeclaration_0ElementType() {
			return new IGrammarAwareElementType("Action_TURN_ONEnumLiteralDeclaration_0_ELEMENT_TYPE", MyDslLanguage.INSTANCE, GRAMMAR_ACCESS.getActionAccess().getTURN_ONEnumLiteralDeclaration_0());
		}
		public static IGrammarAwareElementType createAction_TURN_ONTurn_onKeyword_0_0ElementType() {
			return new IGrammarAwareElementType("Action_TURN_ONTurn_onKeyword_0_0_ELEMENT_TYPE", MyDslLanguage.INSTANCE, GRAMMAR_ACCESS.getActionAccess().getTURN_ONTurn_onKeyword_0_0());
		}
		public static IGrammarAwareElementType createAction_TURN_OFFEnumLiteralDeclaration_1ElementType() {
			return new IGrammarAwareElementType("Action_TURN_OFFEnumLiteralDeclaration_1_ELEMENT_TYPE", MyDslLanguage.INSTANCE, GRAMMAR_ACCESS.getActionAccess().getTURN_OFFEnumLiteralDeclaration_1());
		}
		public static IGrammarAwareElementType createAction_TURN_OFFTurn_offKeyword_1_0ElementType() {
			return new IGrammarAwareElementType("Action_TURN_OFFTurn_offKeyword_1_0_ELEMENT_TYPE", MyDslLanguage.INSTANCE, GRAMMAR_ACCESS.getActionAccess().getTURN_OFFTurn_offKeyword_1_0());
		}
	}

	public static final IGrammarAwareElementType Action_ELEMENT_TYPE = associate(ActionFactory.createActionElementType());

	public static final IGrammarAwareElementType Action_Alternatives_ELEMENT_TYPE = associate(ActionFactory.createAction_AlternativesElementType());

	public static final IGrammarAwareElementType Action_TURN_ONEnumLiteralDeclaration_0_ELEMENT_TYPE = associate(ActionFactory.createAction_TURN_ONEnumLiteralDeclaration_0ElementType());

	public static final IGrammarAwareElementType Action_TURN_ONTurn_onKeyword_0_0_ELEMENT_TYPE = associate(ActionFactory.createAction_TURN_ONTurn_onKeyword_0_0ElementType());

	public static final IGrammarAwareElementType Action_TURN_OFFEnumLiteralDeclaration_1_ELEMENT_TYPE = associate(ActionFactory.createAction_TURN_OFFEnumLiteralDeclaration_1ElementType());

	public static final IGrammarAwareElementType Action_TURN_OFFTurn_offKeyword_1_0_ELEMENT_TYPE = associate(ActionFactory.createAction_TURN_OFFTurn_offKeyword_1_0ElementType());

	private static class EntityFactory {
		public static IGrammarAwareElementType createEntityElementType() {
			return new IGrammarAwareElementType("Entity_ELEMENT_TYPE", MyDslLanguage.INSTANCE, GRAMMAR_ACCESS.getEntityRule());
		}
		public static IGrammarAwareElementType createEntity_AlternativesElementType() {
			return new IGrammarAwareElementType("Entity_Alternatives_ELEMENT_TYPE", MyDslLanguage.INSTANCE, GRAMMAR_ACCESS.getEntityAccess().getAlternatives());
		}
		public static IGrammarAwareElementType createEntity_LIGHT_BULBEnumLiteralDeclaration_0ElementType() {
			return new IGrammarAwareElementType("Entity_LIGHT_BULBEnumLiteralDeclaration_0_ELEMENT_TYPE", MyDslLanguage.INSTANCE, GRAMMAR_ACCESS.getEntityAccess().getLIGHT_BULBEnumLiteralDeclaration_0());
		}
		public static IGrammarAwareElementType createEntity_LIGHT_BULBLight_bulbKeyword_0_0ElementType() {
			return new IGrammarAwareElementType("Entity_LIGHT_BULBLight_bulbKeyword_0_0_ELEMENT_TYPE", MyDslLanguage.INSTANCE, GRAMMAR_ACCESS.getEntityAccess().getLIGHT_BULBLight_bulbKeyword_0_0());
		}
		public static IGrammarAwareElementType createEntity_FANEnumLiteralDeclaration_1ElementType() {
			return new IGrammarAwareElementType("Entity_FANEnumLiteralDeclaration_1_ELEMENT_TYPE", MyDslLanguage.INSTANCE, GRAMMAR_ACCESS.getEntityAccess().getFANEnumLiteralDeclaration_1());
		}
		public static IGrammarAwareElementType createEntity_FANFanKeyword_1_0ElementType() {
			return new IGrammarAwareElementType("Entity_FANFanKeyword_1_0_ELEMENT_TYPE", MyDslLanguage.INSTANCE, GRAMMAR_ACCESS.getEntityAccess().getFANFanKeyword_1_0());
		}
		public static IGrammarAwareElementType createEntity_ACEnumLiteralDeclaration_2ElementType() {
			return new IGrammarAwareElementType("Entity_ACEnumLiteralDeclaration_2_ELEMENT_TYPE", MyDslLanguage.INSTANCE, GRAMMAR_ACCESS.getEntityAccess().getACEnumLiteralDeclaration_2());
		}
		public static IGrammarAwareElementType createEntity_ACAcKeyword_2_0ElementType() {
			return new IGrammarAwareElementType("Entity_ACAcKeyword_2_0_ELEMENT_TYPE", MyDslLanguage.INSTANCE, GRAMMAR_ACCESS.getEntityAccess().getACAcKeyword_2_0());
		}
	}

	public static final IGrammarAwareElementType Entity_ELEMENT_TYPE = associate(EntityFactory.createEntityElementType());

	public static final IGrammarAwareElementType Entity_Alternatives_ELEMENT_TYPE = associate(EntityFactory.createEntity_AlternativesElementType());

	public static final IGrammarAwareElementType Entity_LIGHT_BULBEnumLiteralDeclaration_0_ELEMENT_TYPE = associate(EntityFactory.createEntity_LIGHT_BULBEnumLiteralDeclaration_0ElementType());

	public static final IGrammarAwareElementType Entity_LIGHT_BULBLight_bulbKeyword_0_0_ELEMENT_TYPE = associate(EntityFactory.createEntity_LIGHT_BULBLight_bulbKeyword_0_0ElementType());

	public static final IGrammarAwareElementType Entity_FANEnumLiteralDeclaration_1_ELEMENT_TYPE = associate(EntityFactory.createEntity_FANEnumLiteralDeclaration_1ElementType());

	public static final IGrammarAwareElementType Entity_FANFanKeyword_1_0_ELEMENT_TYPE = associate(EntityFactory.createEntity_FANFanKeyword_1_0ElementType());

	public static final IGrammarAwareElementType Entity_ACEnumLiteralDeclaration_2_ELEMENT_TYPE = associate(EntityFactory.createEntity_ACEnumLiteralDeclaration_2ElementType());

	public static final IGrammarAwareElementType Entity_ACAcKeyword_2_0_ELEMENT_TYPE = associate(EntityFactory.createEntity_ACAcKeyword_2_0ElementType());

	@Override
	public IFileElementType getFileType() {
		return FILE_TYPE;
	}

	@Override
	public IGrammarAwareElementType findElementType(EObject grammarElement) {
		return GRAMMAR_ELEMENT_TYPE.get(grammarElement);
	}
	
	public IGrammarAwareElementType getRulesElementType() {
		return Rules_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getRules_RuleFragmentsAssignmentElementType() {
		return Rules_RuleFragmentsAssignment_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getRules_RuleFragmentsRuleFragmentsParserRuleCall_0ElementType() {
		return Rules_RuleFragmentsRuleFragmentsParserRuleCall_0_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getRuleFragmentsElementType() {
		return RuleFragments_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getRuleFragments_GroupElementType() {
		return RuleFragments_Group_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getRuleFragments_RuleKeyword_0ElementType() {
		return RuleFragments_RuleKeyword_0_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getRuleFragments_RuleNameAssignment_1ElementType() {
		return RuleFragments_RuleNameAssignment_1_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getRuleFragments_RuleNameIDTerminalRuleCall_1_0ElementType() {
		return RuleFragments_RuleNameIDTerminalRuleCall_1_0_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getRuleFragments_LeftCurlyBracketKeyword_2ElementType() {
		return RuleFragments_LeftCurlyBracketKeyword_2_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getRuleFragments_RuleBodyAssignment_3ElementType() {
		return RuleFragments_RuleBodyAssignment_3_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getRuleFragments_RuleBodyRuleBodyParserRuleCall_3_0ElementType() {
		return RuleFragments_RuleBodyRuleBodyParserRuleCall_3_0_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getRuleFragments_RightCurlyBracketKeyword_4ElementType() {
		return RuleFragments_RightCurlyBracketKeyword_4_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getRuleBodyElementType() {
		return RuleBody_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getRuleBody_GroupElementType() {
		return RuleBody_Group_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getRuleBody_WhenKeyword_0ElementType() {
		return RuleBody_WhenKeyword_0_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getRuleBody_EventAssignment_1ElementType() {
		return RuleBody_EventAssignment_1_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getRuleBody_EventEventParserRuleCall_1_0ElementType() {
		return RuleBody_EventEventParserRuleCall_1_0_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getRuleBody_SubEventAssignment_2ElementType() {
		return RuleBody_SubEventAssignment_2_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getRuleBody_SubEventSubEventParserRuleCall_2_0ElementType() {
		return RuleBody_SubEventSubEventParserRuleCall_2_0_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getEventElementType() {
		return Event_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getEvent_GroupElementType() {
		return Event_Group_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getEvent_AttributeAssignment_0ElementType() {
		return Event_AttributeAssignment_0_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getEvent_AttributeAttributeEnumRuleCall_0_0ElementType() {
		return Event_AttributeAttributeEnumRuleCall_0_0_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getEvent_SymbolAssignment_1ElementType() {
		return Event_SymbolAssignment_1_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getEvent_SymbolSymbolEnumRuleCall_1_0ElementType() {
		return Event_SymbolSymbolEnumRuleCall_1_0_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getEvent_ValueAssignment_2ElementType() {
		return Event_ValueAssignment_2_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getEvent_ValueINTTerminalRuleCall_2_0ElementType() {
		return Event_ValueINTTerminalRuleCall_2_0_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getAttributeElementType() {
		return Attribute_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getAttribute_AlternativesElementType() {
		return Attribute_Alternatives_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getAttribute_TEMPERATUREEnumLiteralDeclaration_0ElementType() {
		return Attribute_TEMPERATUREEnumLiteralDeclaration_0_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getAttribute_TEMPERATURETemperatureKeyword_0_0ElementType() {
		return Attribute_TEMPERATURETemperatureKeyword_0_0_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getAttribute_VIBRATIONEnumLiteralDeclaration_1ElementType() {
		return Attribute_VIBRATIONEnumLiteralDeclaration_1_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getAttribute_VIBRATIONVibrationKeyword_1_0ElementType() {
		return Attribute_VIBRATIONVibrationKeyword_1_0_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getAttribute_HUMIDITYEnumLiteralDeclaration_2ElementType() {
		return Attribute_HUMIDITYEnumLiteralDeclaration_2_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getAttribute_HUMIDITYHumidityKeyword_2_0ElementType() {
		return Attribute_HUMIDITYHumidityKeyword_2_0_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getSymbolElementType() {
		return Symbol_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getSymbol_AlternativesElementType() {
		return Symbol_Alternatives_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getSymbol_GREATEREnumLiteralDeclaration_0ElementType() {
		return Symbol_GREATEREnumLiteralDeclaration_0_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getSymbol_GREATERLessThanSignKeyword_0_0ElementType() {
		return Symbol_GREATERLessThanSignKeyword_0_0_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getSymbol_LESSEnumLiteralDeclaration_1ElementType() {
		return Symbol_LESSEnumLiteralDeclaration_1_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getSymbol_LESSGreaterThanSignKeyword_1_0ElementType() {
		return Symbol_LESSGreaterThanSignKeyword_1_0_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getSubEventElementType() {
		return SubEvent_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getSubEvent_GroupElementType() {
		return SubEvent_Group_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getSubEvent_ThenKeyword_0ElementType() {
		return SubEvent_ThenKeyword_0_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getSubEvent_AmountEventAssignment_1ElementType() {
		return SubEvent_AmountEventAssignment_1_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getSubEvent_AmountEventActionEnumRuleCall_1_0ElementType() {
		return SubEvent_AmountEventActionEnumRuleCall_1_0_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getSubEvent_EntityAssignment_2ElementType() {
		return SubEvent_EntityAssignment_2_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getSubEvent_EntityEntityEnumRuleCall_2_0ElementType() {
		return SubEvent_EntityEntityEnumRuleCall_2_0_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getActionElementType() {
		return Action_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getAction_AlternativesElementType() {
		return Action_Alternatives_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getAction_TURN_ONEnumLiteralDeclaration_0ElementType() {
		return Action_TURN_ONEnumLiteralDeclaration_0_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getAction_TURN_ONTurn_onKeyword_0_0ElementType() {
		return Action_TURN_ONTurn_onKeyword_0_0_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getAction_TURN_OFFEnumLiteralDeclaration_1ElementType() {
		return Action_TURN_OFFEnumLiteralDeclaration_1_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getAction_TURN_OFFTurn_offKeyword_1_0ElementType() {
		return Action_TURN_OFFTurn_offKeyword_1_0_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getEntityElementType() {
		return Entity_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getEntity_AlternativesElementType() {
		return Entity_Alternatives_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getEntity_LIGHT_BULBEnumLiteralDeclaration_0ElementType() {
		return Entity_LIGHT_BULBEnumLiteralDeclaration_0_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getEntity_LIGHT_BULBLight_bulbKeyword_0_0ElementType() {
		return Entity_LIGHT_BULBLight_bulbKeyword_0_0_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getEntity_FANEnumLiteralDeclaration_1ElementType() {
		return Entity_FANEnumLiteralDeclaration_1_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getEntity_FANFanKeyword_1_0ElementType() {
		return Entity_FANFanKeyword_1_0_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getEntity_ACEnumLiteralDeclaration_2ElementType() {
		return Entity_ACEnumLiteralDeclaration_2_ELEMENT_TYPE;
	}
	
	public IGrammarAwareElementType getEntity_ACAcKeyword_2_0ElementType() {
		return Entity_ACAcKeyword_2_0_ELEMENT_TYPE;
	}

}
