/**
 * generated by Xtext 2.9.2
 */
package org.xtext.example.mydsl.myDsl;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EEnum;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.xtext.example.mydsl.myDsl.MyDslFactory
 * @model kind="package"
 * @generated
 */
public interface MyDslPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "myDsl";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.xtext.org/example/mydsl/MyDsl";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "myDsl";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  MyDslPackage eINSTANCE = org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl.init();

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.RulesImpl <em>Rules</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.RulesImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getRules()
   * @generated
   */
  int RULES = 0;

  /**
   * The feature id for the '<em><b>Rule Fragments</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RULES__RULE_FRAGMENTS = 0;

  /**
   * The number of structural features of the '<em>Rules</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RULES_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.RuleFragmentsImpl <em>Rule Fragments</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.RuleFragmentsImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getRuleFragments()
   * @generated
   */
  int RULE_FRAGMENTS = 1;

  /**
   * The feature id for the '<em><b>Rule Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RULE_FRAGMENTS__RULE_NAME = 0;

  /**
   * The feature id for the '<em><b>Rule Body</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RULE_FRAGMENTS__RULE_BODY = 1;

  /**
   * The number of structural features of the '<em>Rule Fragments</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RULE_FRAGMENTS_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.RuleBodyImpl <em>Rule Body</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.RuleBodyImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getRuleBody()
   * @generated
   */
  int RULE_BODY = 2;

  /**
   * The feature id for the '<em><b>Payer Event</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RULE_BODY__PAYER_EVENT = 0;

  /**
   * The feature id for the '<em><b>Sub Event</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RULE_BODY__SUB_EVENT = 1;

  /**
   * The number of structural features of the '<em>Rule Body</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RULE_BODY_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.PayerEventImpl <em>Payer Event</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.PayerEventImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getPayerEvent()
   * @generated
   */
  int PAYER_EVENT = 3;

  /**
   * The feature id for the '<em><b>Payer Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PAYER_EVENT__PAYER_NAME = 0;

  /**
   * The feature id for the '<em><b>Payer Event Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PAYER_EVENT__PAYER_EVENT_NAME = 1;

  /**
   * The feature id for the '<em><b>Symbol</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PAYER_EVENT__SYMBOL = 2;

  /**
   * The feature id for the '<em><b>Amount</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PAYER_EVENT__AMOUNT = 3;

  /**
   * The number of structural features of the '<em>Payer Event</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PAYER_EVENT_FEATURE_COUNT = 4;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.SubEventImpl <em>Sub Event</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.SubEventImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getSubEvent()
   * @generated
   */
  int SUB_EVENT = 4;

  /**
   * The feature id for the '<em><b>Amount Event</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SUB_EVENT__AMOUNT_EVENT = 0;

  /**
   * The feature id for the '<em><b>Amount</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SUB_EVENT__AMOUNT = 1;

  /**
   * The feature id for the '<em><b>Payer Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SUB_EVENT__PAYER_NAME = 2;

  /**
   * The number of structural features of the '<em>Sub Event</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SUB_EVENT_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.PayerName <em>Payer Name</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.PayerName
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getPayerName()
   * @generated
   */
  int PAYER_NAME = 5;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.PayerEventName <em>Payer Event Name</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.PayerEventName
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getPayerEventName()
   * @generated
   */
  int PAYER_EVENT_NAME = 6;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.Symbol <em>Symbol</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.Symbol
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getSymbol()
   * @generated
   */
  int SYMBOL = 7;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.AmountEvent <em>Amount Event</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.AmountEvent
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getAmountEvent()
   * @generated
   */
  int AMOUNT_EVENT = 8;


  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.Rules <em>Rules</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Rules</em>'.
   * @see org.xtext.example.mydsl.myDsl.Rules
   * @generated
   */
  EClass getRules();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl.myDsl.Rules#getRuleFragments <em>Rule Fragments</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Rule Fragments</em>'.
   * @see org.xtext.example.mydsl.myDsl.Rules#getRuleFragments()
   * @see #getRules()
   * @generated
   */
  EReference getRules_RuleFragments();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.RuleFragments <em>Rule Fragments</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Rule Fragments</em>'.
   * @see org.xtext.example.mydsl.myDsl.RuleFragments
   * @generated
   */
  EClass getRuleFragments();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.RuleFragments#getRuleName <em>Rule Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Rule Name</em>'.
   * @see org.xtext.example.mydsl.myDsl.RuleFragments#getRuleName()
   * @see #getRuleFragments()
   * @generated
   */
  EAttribute getRuleFragments_RuleName();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.myDsl.RuleFragments#getRuleBody <em>Rule Body</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Rule Body</em>'.
   * @see org.xtext.example.mydsl.myDsl.RuleFragments#getRuleBody()
   * @see #getRuleFragments()
   * @generated
   */
  EReference getRuleFragments_RuleBody();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.RuleBody <em>Rule Body</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Rule Body</em>'.
   * @see org.xtext.example.mydsl.myDsl.RuleBody
   * @generated
   */
  EClass getRuleBody();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.myDsl.RuleBody#getPayerEvent <em>Payer Event</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Payer Event</em>'.
   * @see org.xtext.example.mydsl.myDsl.RuleBody#getPayerEvent()
   * @see #getRuleBody()
   * @generated
   */
  EReference getRuleBody_PayerEvent();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl.myDsl.RuleBody#getSubEvent <em>Sub Event</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Sub Event</em>'.
   * @see org.xtext.example.mydsl.myDsl.RuleBody#getSubEvent()
   * @see #getRuleBody()
   * @generated
   */
  EReference getRuleBody_SubEvent();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.PayerEvent <em>Payer Event</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Payer Event</em>'.
   * @see org.xtext.example.mydsl.myDsl.PayerEvent
   * @generated
   */
  EClass getPayerEvent();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.PayerEvent#getPayerName <em>Payer Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Payer Name</em>'.
   * @see org.xtext.example.mydsl.myDsl.PayerEvent#getPayerName()
   * @see #getPayerEvent()
   * @generated
   */
  EAttribute getPayerEvent_PayerName();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.PayerEvent#getPayerEventName <em>Payer Event Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Payer Event Name</em>'.
   * @see org.xtext.example.mydsl.myDsl.PayerEvent#getPayerEventName()
   * @see #getPayerEvent()
   * @generated
   */
  EAttribute getPayerEvent_PayerEventName();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.PayerEvent#getSymbol <em>Symbol</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Symbol</em>'.
   * @see org.xtext.example.mydsl.myDsl.PayerEvent#getSymbol()
   * @see #getPayerEvent()
   * @generated
   */
  EAttribute getPayerEvent_Symbol();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.PayerEvent#getAmount <em>Amount</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Amount</em>'.
   * @see org.xtext.example.mydsl.myDsl.PayerEvent#getAmount()
   * @see #getPayerEvent()
   * @generated
   */
  EAttribute getPayerEvent_Amount();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.SubEvent <em>Sub Event</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Sub Event</em>'.
   * @see org.xtext.example.mydsl.myDsl.SubEvent
   * @generated
   */
  EClass getSubEvent();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.SubEvent#getAmountEvent <em>Amount Event</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Amount Event</em>'.
   * @see org.xtext.example.mydsl.myDsl.SubEvent#getAmountEvent()
   * @see #getSubEvent()
   * @generated
   */
  EAttribute getSubEvent_AmountEvent();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.SubEvent#getAmount <em>Amount</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Amount</em>'.
   * @see org.xtext.example.mydsl.myDsl.SubEvent#getAmount()
   * @see #getSubEvent()
   * @generated
   */
  EAttribute getSubEvent_Amount();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.SubEvent#getPayerName <em>Payer Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Payer Name</em>'.
   * @see org.xtext.example.mydsl.myDsl.SubEvent#getPayerName()
   * @see #getSubEvent()
   * @generated
   */
  EAttribute getSubEvent_PayerName();

  /**
   * Returns the meta object for enum '{@link org.xtext.example.mydsl.myDsl.PayerName <em>Payer Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Payer Name</em>'.
   * @see org.xtext.example.mydsl.myDsl.PayerName
   * @generated
   */
  EEnum getPayerName();

  /**
   * Returns the meta object for enum '{@link org.xtext.example.mydsl.myDsl.PayerEventName <em>Payer Event Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Payer Event Name</em>'.
   * @see org.xtext.example.mydsl.myDsl.PayerEventName
   * @generated
   */
  EEnum getPayerEventName();

  /**
   * Returns the meta object for enum '{@link org.xtext.example.mydsl.myDsl.Symbol <em>Symbol</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Symbol</em>'.
   * @see org.xtext.example.mydsl.myDsl.Symbol
   * @generated
   */
  EEnum getSymbol();

  /**
   * Returns the meta object for enum '{@link org.xtext.example.mydsl.myDsl.AmountEvent <em>Amount Event</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Amount Event</em>'.
   * @see org.xtext.example.mydsl.myDsl.AmountEvent
   * @generated
   */
  EEnum getAmountEvent();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  MyDslFactory getMyDslFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.RulesImpl <em>Rules</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.RulesImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getRules()
     * @generated
     */
    EClass RULES = eINSTANCE.getRules();

    /**
     * The meta object literal for the '<em><b>Rule Fragments</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference RULES__RULE_FRAGMENTS = eINSTANCE.getRules_RuleFragments();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.RuleFragmentsImpl <em>Rule Fragments</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.RuleFragmentsImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getRuleFragments()
     * @generated
     */
    EClass RULE_FRAGMENTS = eINSTANCE.getRuleFragments();

    /**
     * The meta object literal for the '<em><b>Rule Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute RULE_FRAGMENTS__RULE_NAME = eINSTANCE.getRuleFragments_RuleName();

    /**
     * The meta object literal for the '<em><b>Rule Body</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference RULE_FRAGMENTS__RULE_BODY = eINSTANCE.getRuleFragments_RuleBody();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.RuleBodyImpl <em>Rule Body</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.RuleBodyImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getRuleBody()
     * @generated
     */
    EClass RULE_BODY = eINSTANCE.getRuleBody();

    /**
     * The meta object literal for the '<em><b>Payer Event</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference RULE_BODY__PAYER_EVENT = eINSTANCE.getRuleBody_PayerEvent();

    /**
     * The meta object literal for the '<em><b>Sub Event</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference RULE_BODY__SUB_EVENT = eINSTANCE.getRuleBody_SubEvent();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.PayerEventImpl <em>Payer Event</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.PayerEventImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getPayerEvent()
     * @generated
     */
    EClass PAYER_EVENT = eINSTANCE.getPayerEvent();

    /**
     * The meta object literal for the '<em><b>Payer Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PAYER_EVENT__PAYER_NAME = eINSTANCE.getPayerEvent_PayerName();

    /**
     * The meta object literal for the '<em><b>Payer Event Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PAYER_EVENT__PAYER_EVENT_NAME = eINSTANCE.getPayerEvent_PayerEventName();

    /**
     * The meta object literal for the '<em><b>Symbol</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PAYER_EVENT__SYMBOL = eINSTANCE.getPayerEvent_Symbol();

    /**
     * The meta object literal for the '<em><b>Amount</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PAYER_EVENT__AMOUNT = eINSTANCE.getPayerEvent_Amount();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.SubEventImpl <em>Sub Event</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.SubEventImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getSubEvent()
     * @generated
     */
    EClass SUB_EVENT = eINSTANCE.getSubEvent();

    /**
     * The meta object literal for the '<em><b>Amount Event</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SUB_EVENT__AMOUNT_EVENT = eINSTANCE.getSubEvent_AmountEvent();

    /**
     * The meta object literal for the '<em><b>Amount</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SUB_EVENT__AMOUNT = eINSTANCE.getSubEvent_Amount();

    /**
     * The meta object literal for the '<em><b>Payer Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SUB_EVENT__PAYER_NAME = eINSTANCE.getSubEvent_PayerName();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.PayerName <em>Payer Name</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.PayerName
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getPayerName()
     * @generated
     */
    EEnum PAYER_NAME = eINSTANCE.getPayerName();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.PayerEventName <em>Payer Event Name</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.PayerEventName
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getPayerEventName()
     * @generated
     */
    EEnum PAYER_EVENT_NAME = eINSTANCE.getPayerEventName();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.Symbol <em>Symbol</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.Symbol
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getSymbol()
     * @generated
     */
    EEnum SYMBOL = eINSTANCE.getSymbol();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.AmountEvent <em>Amount Event</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.AmountEvent
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getAmountEvent()
     * @generated
     */
    EEnum AMOUNT_EVENT = eINSTANCE.getAmountEvent();

  }

} //MyDslPackage
