/**
 * generated by Xtext 2.9.2
 */
package org.xtext.example.mydsl.myDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Payer Event</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.PayerEvent#getPayerName <em>Payer Name</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.PayerEvent#getPayerEventName <em>Payer Event Name</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.PayerEvent#getSymbol <em>Symbol</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.PayerEvent#getAmount <em>Amount</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getPayerEvent()
 * @model
 * @generated
 */
public interface PayerEvent extends EObject
{
  /**
   * Returns the value of the '<em><b>Payer Name</b></em>' attribute.
   * The literals are from the enumeration {@link org.xtext.example.mydsl.myDsl.PayerName}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Payer Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Payer Name</em>' attribute.
   * @see org.xtext.example.mydsl.myDsl.PayerName
   * @see #setPayerName(PayerName)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getPayerEvent_PayerName()
   * @model
   * @generated
   */
  PayerName getPayerName();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.PayerEvent#getPayerName <em>Payer Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Payer Name</em>' attribute.
   * @see org.xtext.example.mydsl.myDsl.PayerName
   * @see #getPayerName()
   * @generated
   */
  void setPayerName(PayerName value);

  /**
   * Returns the value of the '<em><b>Payer Event Name</b></em>' attribute.
   * The literals are from the enumeration {@link org.xtext.example.mydsl.myDsl.PayerEventName}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Payer Event Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Payer Event Name</em>' attribute.
   * @see org.xtext.example.mydsl.myDsl.PayerEventName
   * @see #setPayerEventName(PayerEventName)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getPayerEvent_PayerEventName()
   * @model
   * @generated
   */
  PayerEventName getPayerEventName();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.PayerEvent#getPayerEventName <em>Payer Event Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Payer Event Name</em>' attribute.
   * @see org.xtext.example.mydsl.myDsl.PayerEventName
   * @see #getPayerEventName()
   * @generated
   */
  void setPayerEventName(PayerEventName value);

  /**
   * Returns the value of the '<em><b>Symbol</b></em>' attribute.
   * The literals are from the enumeration {@link org.xtext.example.mydsl.myDsl.Symbol}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Symbol</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Symbol</em>' attribute.
   * @see org.xtext.example.mydsl.myDsl.Symbol
   * @see #setSymbol(Symbol)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getPayerEvent_Symbol()
   * @model
   * @generated
   */
  Symbol getSymbol();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.PayerEvent#getSymbol <em>Symbol</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Symbol</em>' attribute.
   * @see org.xtext.example.mydsl.myDsl.Symbol
   * @see #getSymbol()
   * @generated
   */
  void setSymbol(Symbol value);

  /**
   * Returns the value of the '<em><b>Amount</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Amount</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Amount</em>' attribute.
   * @see #setAmount(int)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getPayerEvent_Amount()
   * @model
   * @generated
   */
  int getAmount();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.PayerEvent#getAmount <em>Amount</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Amount</em>' attribute.
   * @see #getAmount()
   * @generated
   */
  void setAmount(int value);

} // PayerEvent
