/**
 * generated by Xtext 2.9.2
 */
package org.xtext.example.mydsl.myDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Sub Event</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.SubEvent#getAmountEvent <em>Amount Event</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.SubEvent#getAmount <em>Amount</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.SubEvent#getPayerName <em>Payer Name</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getSubEvent()
 * @model
 * @generated
 */
public interface SubEvent extends EObject
{
  /**
   * Returns the value of the '<em><b>Amount Event</b></em>' attribute.
   * The literals are from the enumeration {@link org.xtext.example.mydsl.myDsl.AmountEvent}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Amount Event</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Amount Event</em>' attribute.
   * @see org.xtext.example.mydsl.myDsl.AmountEvent
   * @see #setAmountEvent(AmountEvent)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getSubEvent_AmountEvent()
   * @model
   * @generated
   */
  AmountEvent getAmountEvent();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.SubEvent#getAmountEvent <em>Amount Event</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Amount Event</em>' attribute.
   * @see org.xtext.example.mydsl.myDsl.AmountEvent
   * @see #getAmountEvent()
   * @generated
   */
  void setAmountEvent(AmountEvent value);

  /**
   * Returns the value of the '<em><b>Amount</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Amount</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Amount</em>' attribute.
   * @see #setAmount(int)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getSubEvent_Amount()
   * @model
   * @generated
   */
  int getAmount();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.SubEvent#getAmount <em>Amount</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Amount</em>' attribute.
   * @see #getAmount()
   * @generated
   */
  void setAmount(int value);

  /**
   * Returns the value of the '<em><b>Payer Name</b></em>' attribute.
   * The literals are from the enumeration {@link org.xtext.example.mydsl.myDsl.PayerName}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Payer Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Payer Name</em>' attribute.
   * @see org.xtext.example.mydsl.myDsl.PayerName
   * @see #setPayerName(PayerName)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getSubEvent_PayerName()
   * @model
   * @generated
   */
  PayerName getPayerName();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.SubEvent#getPayerName <em>Payer Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Payer Name</em>' attribute.
   * @see org.xtext.example.mydsl.myDsl.PayerName
   * @see #getPayerName()
   * @generated
   */
  void setPayerName(PayerName value);

} // SubEvent
